### ISSUE TITLE
Internal Server Error - Fresh Install

### ISSUE THREAD

**Issue by Rionoskae** [opinkerfi/adagios#208]
Did the code get updatedrecently? Or am I crazy....

Getting Internal Server error on fresh install of ADagios on CentOS 6.4...

I've previously installed Adagios several times in the last week for various testing without any issues.....

Attempting once more on CentOS 6.1 ( to try to integrate Adagios w/ OMD ) Will post a screenshot of Issue & error logs if it re-occurs on 6.1 Fresh install -or- close case if it is non-existant.

**Comment by sri04518** [comment]
Guys, need your help in fixing the issue. Able to load the page nagios but adagios is throwing an error as internal server error. It's a fresh installation using the https://github.com/opinkerfi/adagios/wiki/Install-guide on centos 7.3.
Error it is showing in the logs as
-----------------------------------
   00:30:52.545787    [:error] [pid 1070] Traceback (most recent call last):
   00:30:52.545796    [:error] [pid 1070]   File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
   00:30:52.545815    [:error] [pid 1070]     response = get_response(request)
   00:30:52.545822    [:error] [pid 1070]   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 244, in _legacy_get_response
   00:30:52.545829    [:error] [pid 1070]     response = middleware_method(request)
   00:30:52.545835    [:error] [pid 1070]   File "/usr/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in process_request
   00:30:52.545840    [:error] [pid 1070]     i18n_patterns_used, prefixed_default_language = is_language_prefix_patterns_used(urlconf)
   00:30:52.545846    [:error] [pid 1070]   File "/usr/lib/python2.7/site-packages/django/utils/lru_cache.py", line 100, in wrapper
   00:30:52.545852    [:error] [pid 1070]     result = user_function(*args, **kwds)
   00:30:52.545857    [:error] [pid 1070]   File "/usr/lib/python2.7/site-packages/django/conf/urls/i18n.py", line 29, in is_language_prefix_patterns_used
   00:30:52.545864    [:error] [pid 1070]     for url_pattern in get_resolver(urlconf).url_patterns:
   00:30:52.545869    [:error] [pid 1070]   File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
   00:30:52.545876    [:error] [pid 1070]     res = instance.__dict__[self.name] = self.func(instance)
   00:30:52.545881    [:error] [pid 1070]   File "/usr/lib/python2.7/site-packages/django/urls/resolvers.py", line 407, in url_patterns
   00:30:52.545888    [:error] [pid 1070]     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
   00:30:52.545894    [:error] [pid 1070]   File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
   00:30:52.545900    [:error] [pid 1070]     res = instance.__dict__[self.name] = self.func(instance)
   00:30:52.545905    [:error] [pid 1070]   File "/usr/lib/python2.7/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
   00:30:52.545911    [:error] [pid 1070]     return import_module(self.urlconf_name)
   00:30:52.545917    [:error] [pid 1070]   File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
   00:30:52.545923    [:error] [pid 1070]     __import__(name)
   00:30:52.545928    [:error] [pid 1070]   File "/usr/lib/python2.7/site-packages/adagios/urls.py", line 18, in <module>
   00:30:52.545934    [:error] [pid 1070]     from django.conf.urls import url, patterns, include
   00:30:52.545939    [:error] [pid 1070] ImportError: cannot import name patterns
   00:30:52.596750    [:error] [pid 1070]    mod_wsgi (pid=1070): Exception occurred processing WSGI script '/usr/lib/python2.7/site-packages/adagios/wsgi.py'.
   00:30:52.596854    [:error] [pid 1070]    Traceback (most recent call last):
   00:30:52.596883    [:error] [pid 1070]      File "/usr/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
   00:30:52.596925    [:error] [pid 1070]        response = self.get_response(request)
   00:30:52.596936    [:error] [pid 1070]      File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
   00:30:52.596955    [:error] [pid 1070]        response = self._middleware_chain(request)
   00:30:52.596965    [:error] [pid 1070]      File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
   00:30:52.596981    [:error] [pid 1070]        response = response_for_exception(request, exc)
   00:30:52.597006    [:error] [pid 1070]      File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
   00:30:52.597023    [:error] [pid 1070]        response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
   00:30:52.597033    [:error] [pid 1070]      File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
   00:30:52.597048    [:error] [pid 1070]        return debug.technical_500_response(request, *exc_info)
   00:30:52.597057    [:error] [pid 1070]      File "/usr/lib/python2.7/site-packages/django/views/debug.py", line 84, in technical_500_response
   00:30:52.597074    [:error] [pid 1070]        html = reporter.get_traceback_html()
   00:30:52.597083    [:error] [pid 1070]      File "/usr/lib/python2.7/site-packages/django/views/debug.py", line 328, in get_traceback_html
   00:30:52.597098    [:error] [pid 1070]        return t.render(c)
   00:30:52.597108    [:error] [pid 1070]      File "/usr/lib/python2.7/site-packages/django/template/base.py", line 207, in render
   00:30:52.597124    [:error] [pid 1070]        return self._render(context)
   00:30:52.597133    [:error] [pid 1070]      File "/usr/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
   00:30:52.597148    [:error] [pid 1070]        return self.nodelist.render(context)
   00:30:52.597157    [:error] [pid 1070]      File "/usr/lib/python2.7/site-packages/django/template/base.py", line 990, in render
   00:30:52.597172    [:error] [pid 1070]        bit = node.render_annotated(context)
   00:30:52.597181    [:error] [pid 1070]      File "/usr/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
   00:30:52.597195    [:error] [pid 1070]        return self.render(context)
   00:30:52.597205    [:error] [pid 1070]      File "/usr/lib/python2.7/site-packages/django/template/base.py", line 1040, in render
   00:30:52.597220    [:error] [pid 1070]        output = self.filter_expression.resolve(context)
   00:30:52.597230    [:error] [pid 1070]      File "/usr/lib/python2.7/site-packages/django/template/base.py", line 732, in resolve
   00:30:52.597244    [:error] [pid 1070]        obj = template_localtime(obj, context.use_tz)
   00:30:52.597254    [:error] [pid 1070]      File "/usr/lib/python2.7/site-packages/django/utils/timezone.py", line 195, in template_localtime
   00:30:52.597269    [:error] [pid 1070]        return localtime(value) if should_convert else value
   00:30:52.597279    [:error] [pid 1070]      File "/usr/lib/python2.7/site-packages/django/utils/timezone.py", line 213, in localtime
   00:30:52.597294    [:error] [pid 1070]        timezone = get_current_timezone()
   00:30:52.597304    [:error] [pid 1070]      File "/usr/lib/python2.7/site-packages/django/utils/timezone.py", line 97, in get_current_timezone
   00:30:52.597318    [:error] [pid 1070]        return getattr(_active, "value", get_default_timezone())
   00:30:52.597328    [:error] [pid 1070]      File "/usr/lib/python2.7/site-packages/django/utils/lru_cache.py", line 124, in wrapper
   00:30:52.597350    [:error] [pid 1070]        result = user_function(*args, **kwds)
   00:30:52.597360    [:error] [pid 1070]      File "/usr/lib/python2.7/site-packages/django/utils/timezone.py", line 79, in get_default_timezone
   00:30:52.597375    [:error] [pid 1070]        return pytz.timezone(settings.TIME_ZONE)
   00:30:52.597385    [:error] [pid 1070]      File "/usr/lib/python2.7/site-packages/pytz/__init__.py", line 156, in timezone
   00:30:52.597400    [:error] [pid 1070]        if zone.upper() == 'UTC':
   00:30:52.597418    [:error] [pid 1070]    AttributeError: 'NoneType' object has no attribute 'upper'

**Comment by nistelroooy** [comment]
Hello ,
I installed Adagios and Nagios 4 several time  but i get an internal Server error on fresh install of ADagios on Rhel 7.5
![interbal](https://user-images.githubusercontent.com/47775560/53003960-70f9bb80-3430-11e9-9224-3ae562f9fd63.PNG)

Here is the output for /etc/httpd/conf/log/error_log :

[Tue Feb 19 10:23:02.693522 2019] [:error] [pid 4147] Internal Server Error: /adagios/
[Tue Feb 19 10:23:02.693591 2019] [:error] [pid 4147] Traceback (most recent call last):
[Tue Feb 19 10:23:02.693604 2019] [:error] [pid 4147]   File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
[Tue Feb 19 10:23:02.693614 2019] [:error] [pid 4147]     response = get_response(request)
[Tue Feb 19 10:23:02.693627 2019] [:error] [pid 4147]   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 244, in _legacy_get_response
[Tue Feb 19 10:23:02.693644 2019] [:error] [pid 4147]     response = middleware_method(request)
[Tue Feb 19 10:23:02.693667 2019] [:error] [pid 4147]   File "/usr/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in process_request
[Tue Feb 19 10:23:02.693679 2019] [:error] [pid 4147]     i18n_patterns_used, prefixed_default_language = is_language_prefix_patterns_used(urlconf)
[Tue Feb 19 10:23:02.693872 2019] [:error] [pid 4147]   File "/usr/lib/python2.7/site-packages/django/utils/lru_cache.py", line 100, in wrapper
[Tue Feb 19 10:23:02.693965 2019] [:error] [pid 4147]     result = user_function(*args, **kwds)
[Tue Feb 19 10:23:02.694028 2019] [:error] [pid 4147]   File "/usr/lib/python2.7/site-packages/django/conf/urls/i18n.py", line 29, in is_language_prefix_patterns_used
[Tue Feb 19 10:23:02.694080 2019] [:error] [pid 4147]     for url_pattern in get_resolver(urlconf).url_patterns:
[Tue Feb 19 10:23:02.694128 2019] [:error] [pid 4147]   File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
[Tue Feb 19 10:23:02.694176 2019] [:error] [pid 4147]     res = instance.__dict__[self.name] = self.func(instance)
[Tue Feb 19 10:23:02.694235 2019] [:error] [pid 4147]   File "/usr/lib/python2.7/site-packages/django/urls/resolvers.py", line 407, in url_patterns
[Tue Feb 19 10:23:02.694281 2019] [:error] [pid 4147]     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
[Tue Feb 19 10:23:02.694321 2019] [:error] [pid 4147]   File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
[Tue Feb 19 10:23:02.694360 2019] [:error] [pid 4147]     res = instance.__dict__[self.name] = self.func(instance)
[Tue Feb 19 10:23:02.694407 2019] [:error] [pid 4147]   File "/usr/lib/python2.7/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
[Tue Feb 19 10:23:02.694454 2019] [:error] [pid 4147]     return import_module(self.urlconf_name)
[Tue Feb 19 10:23:02.694493 2019] [:error] [pid 4147]   File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
[Tue Feb 19 10:23:02.694531 2019] [:error] [pid 4147]     __import__(name)
[Tue Feb 19 10:23:02.694576 2019] [:error] [pid 4147]   File "/usr/lib/python2.7/site-packages/adagios/urls.py", line 18, in <module>
[Tue Feb 19 10:23:02.694615 2019] [:error] [pid 4147]     from django.conf.urls import url, patterns, include
[Tue Feb 19 10:23:02.694660 2019] [:error] [pid 4147] ImportError: cannot import name patterns
[Tue Feb 19 10:23:02.731445 2019] [:error] [pid 4147] [remote 10.2.200.108:52] mod_wsgi (pid=4147): Exception occurred processing WSGI script '/usr/lib/python2.7/site-packages/adagios/wsgi.py'.
[Tue Feb 19 10:23:02.731490 2019] [:error] [pid 4147] [remote 10.2.200.108:52] Traceback (most recent call last):
[Tue Feb 19 10:23:02.731507 2019] [:error] [pid 4147] [remote 10.2.200.108:52]   File "/usr/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
[Tue Feb 19 10:23:02.731540 2019] [:error] [pid 4147] [remote 10.2.200.108:52]     response = self.get_response(request)
[Tue Feb 19 10:23:02.731550 2019] [:error] [pid 4147] [remote 10.2.200.108:52]   File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
[Tue Feb 19 10:23:02.731563 2019] [:error] [pid 4147] [remote 10.2.200.108:52]     response = self._middleware_chain(request)
[Tue Feb 19 10:23:02.731570 2019] [:error] [pid 4147] [remote 10.2.200.108:52]   File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
[Tue Feb 19 10:23:02.731582 2019] [:error] [pid 4147] [remote 10.2.200.108:52]     response = response_for_exception(request, exc)
[Tue Feb 19 10:23:02.731589 2019] [:error] [pid 4147] [remote 10.2.200.108:52]   File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
[Tue Feb 19 10:23:02.731600 2019] [:error] [pid 4147] [remote 10.2.200.108:52]     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
[Tue Feb 19 10:23:02.731607 2019] [:error] [pid 4147] [remote 10.2.200.108:52]   File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
[Tue Feb 19 10:23:02.731617 2019] [:error] [pid 4147] [remote 10.2.200.108:52]     return debug.technical_500_response(request, *exc_info)
[Tue Feb 19 10:23:02.731624 2019] [:error] [pid 4147] [remote 10.2.200.108:52]   File "/usr/lib/python2.7/site-packages/django/views/debug.py", line 84, in technical_500_response
[Tue Feb 19 10:23:02.731636 2019] [:error] [pid 4147] [remote 10.2.200.108:52]     html = reporter.get_traceback_html()
[Tue Feb 19 10:23:02.731642 2019] [:error] [pid 4147] [remote 10.2.200.108:52]   File "/usr/lib/python2.7/site-packages/django/views/debug.py", line 328, in get_traceback_html
[Tue Feb 19 10:23:02.731653 2019] [:error] [pid 4147] [remote 10.2.200.108:52]     return t.render(c)
[Tue Feb 19 10:23:02.731660 2019] [:error] [pid 4147] [remote 10.2.200.108:52]   File "/usr/lib/python2.7/site-packages/django/template/base.py", line 207, in render
[Tue Feb 19 10:23:02.731671 2019] [:error] [pid 4147] [remote 10.2.200.108:52]     return self._render(context)
[Tue Feb 19 10:23:02.731678 2019] [:error] [pid 4147] [remote 10.2.200.108:52]   File "/usr/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
[Tue Feb 19 10:23:02.731689 2019] [:error] [pid 4147] [remote 10.2.200.108:52]     return self.nodelist.render(context)
[Tue Feb 19 10:23:02.731696 2019] [:error] [pid 4147] [remote 10.2.200.108:52]   File "/usr/lib/python2.7/site-packages/django/template/base.py", line 990, in render
[Tue Feb 19 10:23:02.731706 2019] [:error] [pid 4147] [remote 10.2.200.108:52]     bit = node.render_annotated(context)
[Tue Feb 19 10:23:02.731713 2019] [:error] [pid 4147] [remote 10.2.200.108:52]   File "/usr/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
[Tue Feb 19 10:23:02.731723 2019] [:error] [pid 4147] [remote 10.2.200.108:52]     return self.render(context)
[Tue Feb 19 10:23:02.731730 2019] [:error] [pid 4147] [remote 10.2.200.108:52]   File "/usr/lib/python2.7/site-packages/django/template/base.py", line 1040, in render
[Tue Feb 19 10:23:02.731740 2019] [:error] [pid 4147] [remote 10.2.200.108:52]     output = self.filter_expression.resolve(context)
[Tue Feb 19 10:23:02.731750 2019] [:error] [pid 4147] [remote 10.2.200.108:52]   File "/usr/lib/python2.7/site-packages/django/template/base.py", line 732, in resolve
[Tue Feb 19 10:23:02.731800 2019] [:error] [pid 4147] [remote 10.2.200.108:52]     obj = template_localtime(obj, context.use_tz)
[Tue Feb 19 10:23:02.731821 2019] [:error] [pid 4147] [remote 10.2.200.108:52]   File "/usr/lib/python2.7/site-packages/django/utils/timezone.py", line 195, in template_localtime
[Tue Feb 19 10:23:02.731847 2019] [:error] [pid 4147] [remote 10.2.200.108:52]     return localtime(value) if should_convert else value
[Tue Feb 19 10:23:02.731869 2019] [:error] [pid 4147] [remote 10.2.200.108:52]   File "/usr/lib/python2.7/site-packages/django/utils/timezone.py", line 213, in localtime
[Tue Feb 19 10:23:02.731895 2019] [:error] [pid 4147] [remote 10.2.200.108:52]     timezone = get_current_timezone()
[Tue Feb 19 10:23:02.731917 2019] [:error] [pid 4147] [remote 10.2.200.108:52]   File "/usr/lib/python2.7/site-packages/django/utils/timezone.py", line 97, in get_current_timezone
[Tue Feb 19 10:23:02.731954 2019] [:error] [pid 4147] [remote 10.2.200.108:52]     return getattr(_active, "value", get_default_timezone())
[Tue Feb 19 10:23:02.731977 2019] [:error] [pid 4147] [remote 10.2.200.108:52]   File "/usr/lib/python2.7/site-packages/django/utils/lru_cache.py", line 124, in wrapper
[Tue Feb 19 10:23:02.732004 2019] [:error] [pid 4147] [remote 10.2.200.108:52]     result = user_function(*args, **kwds)
[Tue Feb 19 10:23:02.732026 2019] [:error] [pid 4147] [remote 10.2.200.108:52]   File "/usr/lib/python2.7/site-packages/django/utils/timezone.py", line 79, in get_default_timezone
[Tue Feb 19 10:23:02.732053 2019] [:error] [pid 4147] [remote 10.2.200.108:52]     return pytz.timezone(settings.TIME_ZONE)
[Tue Feb 19 10:23:02.732075 2019] [:error] [pid 4147] [remote 10.2.200.108:52]   File "/usr/lib/python2.7/site-packages/pytz/__init__.py", line 156, in timezone
[Tue Feb 19 10:23:02.732102 2019] [:error] [pid 4147] [remote 10.2.200.108:52]     if zone.upper() == 'UTC':
[Tue Feb 19 10:23:02.732132 2019] [:error] [pid 4147] [remote 10.2.200.108:52] AttributeError: 'NoneType' object has no attribute 'upper'

Please help me !!

**Comment by gardart** [comment]
Try to uninstall python2-django-1.11 and install Python2-django1.6
