### ISSUE TITLE
Host shows as "Host Down" when host is not down

### ISSUE THREAD

**Issue by wcamarra** [opinkerfi/adagios#222]
Hello!

I was told to post this as a bug report by duerF on IRC.

There is an issue with the status page (Home/Status/Hosts to be exact) where under the "Host Status" column, a host will show down even if it is not. (http://imgur.com/JasoKby). If I select these hosts individually they will show as being as old as Epoch (http://i.imgur.com/dhEWPZh.png), but clearly the hosts are being checked. I have graph information for all of these hosts. 

However, when I added a service that does the same thing as the host check, the Host   Status shows the host as Up, and the status on the individual host begins to work (no longer shows 43+ years).

I am using the Yum repo for my adagios install.

pynag --version: 0.6.1

Please let me know if you require more information.

Thanks!

**Comment by TravellingGuy** [comment]
I'm presently having this exact same problem on 1.6.1.

I'm just setting up a new nagios/adagios (having never used adagios before), and when I add a new host whose initial status is OK, the /status/hosts page shows these hosts as "Host Down". Drilling down into the actual host detail page shows the status as "ok for 45 years, 3 months". In addition, the nagios web interface properly shows the hosts as all "UP" on the host overview page.

If I force a change in the status of the host, setting it to CRITICAL via a passive check, for instance, this will "fix" the problem. Adagios will properly show the host as down, but it will go back to "Host UP" state during the next active check and then everything is fine.

**Comment by ghomem** [comment]
This is happening with

adagios-1.6.1-1.git.143.fc57957.el6.noarch

Host is UP on Nagios and listed as DOWN on Adagios. But if we click on the host to see that details it appears as UP with status " ok for 45 years, 3 months". This is for a host with no services and a specific check_command.

**Comment by TravellingGuy** [comment]
As @ghomem says (and I noticed the same thing), it only does this for hosts with no services. Once a host has a service, the host shows the proper status.

**Comment by ghomem** [comment]
Note: 

hosts with no services are relevant because one needs to check hosts behind gateways with port forwarding - they might not have any public service besides SSH on a certain port which is checked with the host check_command, in order to represent the host state. Adding a "ping" wouldn't help.
