### ISSUE TITLE
Installer should not create /etc/adagios automatically

### ISSUE THREAD

**Issue by giner** [opinkerfi/adagios#411]
Installer should not create /etc/adagios automatically as this causes failure on installation within normal (non-root) user within custom prefix, for example:
pip install --install-option="--prefix=/opt/adagios" adagios

**Comment by ryepup** [comment]
one downside of this fix; installing from scratch via pip no longer writes /etc/adagios/adagios.conf; copying config files to /etc as a manual step after pip installation.
