### ISSUE TITLE
CentOS/RHEL 7

### ISSUE THREAD

**Issue by tomas-edwardsson** [opinkerfi/adagios#416]
Parent issue for tracking issues running Adagios on CentOS/RHEL7

Status
--------
Install goes through normally using docs from https://github.com/opinkerfi/adagios/wiki/Install-guide/
Adagios fails with errors on django 1.6, see #415

Issues
--------
 * pnp4nagios is en epel-testing, hopefully included in the next couple of weeks, workaround "--enablerepo=epel-testing" when installing it.
 * Cannot run with django 1.6, #415

**Comment by hakong** [comment]
Any news?

**Comment by hiiambo** [comment]
Any update? Would love to install this on my CentOS 7 server.

**Comment by palli** [comment]
With no response from @tomas-edwardsson I can only assume its not being worked on currently.

Any volunteers to help with this ?

**Comment by historicbruno** [comment]
Had no problems installing Adagios on CentOS 7.1 about a month ago.

**Comment by Nozlaf** [comment]
yeah I can confirm it also works fine in centos7.1 just installed it again last week

**Comment by hakong** [comment]
Installing on CentOS 7 works, but I got an error when opening Adagios in a browser:
```
[Fri Jul 17 06:45:11.024385 2015] [:error] [pid 960] [remote 94.142.159.65:24] mod_wsgi (pid=960): Target WSGI script '/usr/lib/python2.7/site-packages/adagios/wsgi.py' cannot be loaded as Python module.
[Fri Jul 17 06:45:11.024426 2015] [:error] [pid 960] [remote 94.142.159.65:24] mod_wsgi (pid=960): Exception occurred processing WSGI script '/usr/lib/python2.7/site-packages/adagios/wsgi.py'.
[Fri Jul 17 06:45:11.024454 2015] [:error] [pid 960] [remote 94.142.159.65:24] Traceback (most recent call last):
[Fri Jul 17 06:45:11.024481 2015] [:error] [pid 960] [remote 94.142.159.65:24]   File "/usr/lib/python2.7/site-packages/adagios/wsgi.py", line 20, in <module>
[Fri Jul 17 06:45:11.024514 2015] [:error] [pid 960] [remote 94.142.159.65:24]     from pkg_resources import require
[Fri Jul 17 06:45:11.024538 2015] [:error] [pid 960] [remote 94.142.159.65:24] ImportError: No module named pkg_resources
```

So I installed python-setuptools and it works fine :)

Updated the wiki to include python-setuptools.
