### ISSUE TITLE
Nagios process control on systemd enabled machines

### ISSUE THREAD

**Issue by tomas-edwardsson** [opinkerfi/adagios#421]
Systemd enabled machines do not have the sysv init script and use systemctl or service commands to control processes.

Another difference is that services run in foreground under systemd. This has the side effect that nagios does not write a pid file which breaks the current way of detecting if nagios is running. To mitigate this "systemctl is-running <service>" should work.

pynag.Control already has code that integrates with systemd and using it exclusively should be the way to go.

Question remains on how to deal with configuring this. Currently there is a parameter called nagios_init_script, I suggest a new one be added called "nagios_service" and if that is defined, use it instead of the nagios_init_script, optionally emitting a warning to the logs. nagios_service would just contain the service name.

**Comment by halfa** [comment]
We met this issue on a debian systemd-enabled system.

```

**Comment by gardart** [comment]
This issue needs to be fixed in Pynag. I'm going to test this on Debian. Will let you know...

**Comment by halfa** [comment]
Would be happy to fix code or test a patch if needed, just point me at the source

**Comment by gardart** [comment]
Hi, please see this pull request https://github.com/pynag/pynag/pull/257 and this commit https://github.com/pynag/pynag/pull/257/commits/584e564ecc9bd00734b1895e4d3384eda4f7c87b

I haven't tested this yet but it should work...
