### ISSUE TITLE
Downtime: wrong date applied (Adagios doesn't like November)

### ISSUE THREAD

**Issue by giner** [opinkerfi/adagios#451]
I choose:
start date: 2014-10-31 17:42
and date: 2014-11-01 08:00

And get:
nagiosadmin: This service has been scheduled for fixed downtime from 2014-10-31 17:42:43 to 2014-12-01 08:00:43. Notifications for the service will not be sent out during that time period.

I choose:
start date: 2014-10-31 17:43
and date: 2014-11-02 19:43

And get:
nagiosadmin: This service has been scheduled for fixed downtime from 2014-10-31 17:43:03 to 2014-12-02 19:43:03. Notifications for the service will not be sent out during that time period. 

I choose:
start date: 2014-11-03 17:50
and date: 2014-11-14 19:50

And get:
nagiosadmin: This service has been scheduled for fixed downtime from 2014-12-03 17:50:04 to 2014-12-14 19:50:04. Notifications for the service will not be sent out during that time period.

**Comment by gardart** [comment]
please open this case again if this is still an issue
