### ISSUE TITLE
unable to install adagios on centos 7

### ISSUE THREAD

**Issue by jonbn** [opinkerfi/adagios#510]
Have installed ok.repo tried  yum --enablerepo=ok-testing install -y adagios okconfig

this is the error i get:

Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: anorien.csc.warwick.ac.uk
 * epel: be.mirror.eurid.eu
 * extras: centos.serverspace.co.uk
 * updates: anorien.csc.warwick.ac.uk
Resolving Dependencies
--> Running transaction check
---> Package adagios.noarch 0:1.6.1-1.git.100.3054aee.el6 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: adagios-1.6.1-1.git.100.3054aee.el6.noarch
--> Processing Dependency: pynag >= 0.8.8 for package: adagios-1.6.1-1.git.100.3054aee.el6.noarch
--> Processing Dependency: python-simplejson for package: adagios-1.6.1-1.git.100.3054aee.el6.noarch
--> Processing Dependency: python-django15 for package: adagios-1.6.1-1.git.100.3054aee.el6.noarch
--> Processing Dependency: mod_wsgi for package: adagios-1.6.1-1.git.100.3054aee.el6.noarch
---> Package okconfig.noarch 0:1.3.0-1.git.0.79bff73.el6 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: okconfig-1.3.0-1.git.0.79bff73.el6.noarch
--> Processing Dependency: winexe for package: okconfig-1.3.0-1.git.0.79bff73.el6.noarch
--> Processing Dependency: python-paramiko for package: okconfig-1.3.0-1.git.0.79bff73.el6.noarch
--> Processing Dependency: nagios-plugins-nrpe for package: okconfig-1.3.0-1.git.0.79bff73.el6.noarch
--> Processing Dependency: nagios-okplugin-mailblacklist for package: okconfig-1.3.0-1.git.0.79bff73.el6.noarch
--> Processing Dependency: nagios-okplugin-check_time for package: okconfig-1.3.0-1.git.0.79bff73.el6.noarch
--> Processing Dependency: nagios-okplugin-check_disks for package: okconfig-1.3.0-1.git.0.79bff73.el6.noarch
--> Processing Dependency: nagios-okplugin-brocade for package: okconfig-1.3.0-1.git.0.79bff73.el6.noarch
--> Processing Dependency: nagios-okplugin-apc for package: okconfig-1.3.0-1.git.0.79bff73.el6.noarch
--> Running transaction check
---> Package adagios.noarch 0:1.6.1-1.git.100.3054aee.el6 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: adagios-1.6.1-1.git.100.3054aee.el6.noarch
--> Processing Dependency: python-django15 for package: adagios-1.6.1-1.git.100.3054aee.el6.noarch
---> Package mod_wsgi.x86_64 0:3.4-12.el7_0 will be installed
---> Package nagios-okplugin-apc.noarch 0:2.1.2-1.git.0.03f7389.el6 will be installed
--> Processing Dependency: perl(Net::SNMP) for package: nagios-okplugin-apc-2.1.2-1.git.0.03f7389.el6.noarch
--> Processing Dependency: perl(Data::Dumper) for package: nagios-okplugin-apc-2.1.2-1.git.0.03f7389.el6.noarch
---> Package nagios-okplugin-brocade.x86_64 0:0.0.5-1.git.0.09dcc39.el6 will be installed
--> Processing Dependency: perl-Nagios-Plugin for package: nagios-okplugin-brocade-0.0.5-1.git.0.09dcc39.el6.x86_64
--> Processing Dependency: perl(Nagios::Plugin) for package: nagios-okplugin-brocade-0.0.5-1.git.0.09dcc39.el6.x86_64
---> Package nagios-okplugin-check_disks.noarch 0:1.0.7-1.git.0.f986b73.el6 will be installed
---> Package nagios-okplugin-check_time.x86_64 0:1.0.3-1.git.0.5f604b8.el6 will be installed
--> Processing Dependency: nagios-nrpe for package: nagios-okplugin-check_time-1.0.3-1.git.0.5f604b8.el6.x86_64
--> Processing Dependency: bc for package: nagios-okplugin-check_time-1.0.3-1.git.0.5f604b8.el6.x86_64
---> Package nagios-okplugin-mailblacklist.noarch 0:1.1-1.git.0.e9222eb.el6 will be installed
--> Processing Dependency: perl(Net::DNS) for package: nagios-okplugin-mailblacklist-1.1-1.git.0.e9222eb.el6.noarch
---> Package nagios-plugins-nrpe.x86_64 0:2.15-2.el7 will be installed
---> Package okconfig.noarch 0:1.3.0-1.git.0.79bff73.el6 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: okconfig-1.3.0-1.git.0.79bff73.el6.noarch
---> Package pynag.noarch 0:0.9.1-1.git.127.0e6a274.el6 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: pynag-0.9.1-1.git.127.0e6a274.el6.noarch
---> Package python-paramiko.noarch 0:1.15.1-1.el7 will be installed
--> Processing Dependency: python-crypto >= 2.1 for package: python-paramiko-1.15.1-1.el7.noarch
--> Processing Dependency: python-ecdsa for package: python-paramiko-1.15.1-1.el7.noarch
---> Package python-simplejson.x86_64 0:3.3.3-1.el7 will be installed
---> Package winexe.x86_64 0:1.1-1.git.0.9d83c1e.el6 will be installed
--> Processing Dependency: liberrors.so(SAMBA_4.0.0RC4)(64bit) for package: winexe-1.1-1.git.0.9d83c1e.el6.x86_64
--> Processing Dependency: libdcerpc-samba.so(SAMBA_4.0.0RC4)(64bit) for package: winexe-1.1-1.git.0.9d83c1e.el6.x86_64
--> Processing Dependency: libcli-ldap.so(SAMBA_4.0.0RC4)(64bit) for package: winexe-1.1-1.git.0.9d83c1e.el6.x86_64
--> Running transaction check
---> Package adagios.noarch 0:1.6.1-1.git.100.3054aee.el6 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: adagios-1.6.1-1.git.100.3054aee.el6.noarch
--> Processing Dependency: python-django15 for package: adagios-1.6.1-1.git.100.3054aee.el6.noarch
---> Package bc.x86_64 0:1.06.95-13.el7 will be installed
---> Package nrpe.x86_64 0:2.15-2.el7 will be installed
---> Package okconfig.noarch 0:1.3.0-1.git.0.79bff73.el6 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: okconfig-1.3.0-1.git.0.79bff73.el6.noarch
---> Package perl-Data-Dumper.x86_64 0:2.145-3.el7 will be installed
---> Package perl-Nagios-Plugin.noarch 0:0.36-7.el7 will be installed
--> Processing Dependency: perl(Params::Validate) for package: perl-Nagios-Plugin-0.36-7.el7.noarch
--> Processing Dependency: perl(Math::Calc::Units) for package: perl-Nagios-Plugin-0.36-7.el7.noarch
--> Processing Dependency: perl(Config::Tiny) for package: perl-Nagios-Plugin-0.36-7.el7.noarch
--> Processing Dependency: perl(Class::Accessor::Fast) for package: perl-Nagios-Plugin-0.36-7.el7.noarch
--> Processing Dependency: perl(Class::Accessor) for package: perl-Nagios-Plugin-0.36-7.el7.noarch
---> Package perl-Net-DNS.x86_64 0:0.72-5.el7 will be installed
--> Processing Dependency: perl(Digest::HMAC_MD5) >= 1 for package: perl-Net-DNS-0.72-5.el7.x86_64
---> Package perl-Net-SNMP.noarch 0:6.0.1-7.el7 will be installed
--> Processing Dependency: perl(Socket6) >= 0.23 for package: perl-Net-SNMP-6.0.1-7.el7.noarch
--> Processing Dependency: perl(Digest::SHA1) for package: perl-Net-SNMP-6.0.1-7.el7.noarch
--> Processing Dependency: perl(Digest::MD5) for package: perl-Net-SNMP-6.0.1-7.el7.noarch
--> Processing Dependency: perl(Crypt::DES) for package: perl-Net-SNMP-6.0.1-7.el7.noarch
---> Package pynag.noarch 0:0.9.1-1.git.127.0e6a274.el6 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: pynag-0.9.1-1.git.127.0e6a274.el6.noarch
---> Package python-crypto.x86_64 0:2.6.1-1.el7.centos will be installed
---> Package python-ecdsa.noarch 0:0.11-3.el7.centos will be installed
--> Processing Dependency: python-six for package: python-ecdsa-0.11-3.el7.centos.noarch
---> Package winexe.x86_64 0:1.1-1.git.0.9d83c1e.el6 will be installed
--> Processing Dependency: liberrors.so(SAMBA_4.0.0RC4)(64bit) for package: winexe-1.1-1.git.0.9d83c1e.el6.x86_64
--> Processing Dependency: libdcerpc-samba.so(SAMBA_4.0.0RC4)(64bit) for package: winexe-1.1-1.git.0.9d83c1e.el6.x86_64
--> Processing Dependency: libcli-ldap.so(SAMBA_4.0.0RC4)(64bit) for package: winexe-1.1-1.git.0.9d83c1e.el6.x86_64
--> Running transaction check
---> Package adagios.noarch 0:1.6.1-1.git.100.3054aee.el6 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: adagios-1.6.1-1.git.100.3054aee.el6.noarch
--> Processing Dependency: python-django15 for package: adagios-1.6.1-1.git.100.3054aee.el6.noarch
---> Package okconfig.noarch 0:1.3.0-1.git.0.79bff73.el6 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: okconfig-1.3.0-1.git.0.79bff73.el6.noarch
---> Package perl-Class-Accessor.noarch 0:0.34-12.el7 will be installed
---> Package perl-Config-Tiny.noarch 0:2.14-7.el7 will be installed
---> Package perl-Crypt-DES.x86_64 0:2.05-20.el7 will be installed
---> Package perl-Digest-HMAC.noarch 0:1.03-5.el7 will be installed
--> Processing Dependency: perl(Digest::SHA) for package: perl-Digest-HMAC-1.03-5.el7.noarch
---> Package perl-Digest-MD5.x86_64 0:2.52-3.el7 will be installed
--> Processing Dependency: perl(Digest::base) >= 1.00 for package: perl-Digest-MD5-2.52-3.el7.x86_64
---> Package perl-Digest-SHA1.x86_64 0:2.13-9.el7 will be installed
---> Package perl-Math-Calc-Units.noarch 0:1.07-9.el7 will be installed
---> Package perl-Params-Validate.x86_64 0:1.08-4.el7 will be installed
--> Processing Dependency: perl(Module::Implementation) for package: perl-Params-Validate-1.08-4.el7.x86_64
---> Package perl-Socket6.x86_64 0:0.23-15.el7 will be installed
---> Package pynag.noarch 0:0.9.1-1.git.127.0e6a274.el6 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: pynag-0.9.1-1.git.127.0e6a274.el6.noarch
---> Package python-six.noarch 0:1.3.0-4.el7 will be installed
---> Package winexe.x86_64 0:1.1-1.git.0.9d83c1e.el6 will be installed
--> Processing Dependency: liberrors.so(SAMBA_4.0.0RC4)(64bit) for package: winexe-1.1-1.git.0.9d83c1e.el6.x86_64
--> Processing Dependency: libdcerpc-samba.so(SAMBA_4.0.0RC4)(64bit) for package: winexe-1.1-1.git.0.9d83c1e.el6.x86_64
--> Processing Dependency: libcli-ldap.so(SAMBA_4.0.0RC4)(64bit) for package: winexe-1.1-1.git.0.9d83c1e.el6.x86_64
--> Running transaction check
---> Package adagios.noarch 0:1.6.1-1.git.100.3054aee.el6 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: adagios-1.6.1-1.git.100.3054aee.el6.noarch
--> Processing Dependency: python-django15 for package: adagios-1.6.1-1.git.100.3054aee.el6.noarch
---> Package okconfig.noarch 0:1.3.0-1.git.0.79bff73.el6 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: okconfig-1.3.0-1.git.0.79bff73.el6.noarch
---> Package perl-Digest.noarch 0:1.17-245.el7 will be installed
---> Package perl-Digest-SHA.x86_64 1:5.85-3.el7 will be installed
---> Package perl-Module-Implementation.noarch 0:0.06-6.el7 will be installed
--> Processing Dependency: perl(Module::Runtime) >= 0.012 for package: perl-Module-Implementation-0.06-6.el7.noarch
--> Processing Dependency: perl(Try::Tiny) for package: perl-Module-Implementation-0.06-6.el7.noarch
---> Package pynag.noarch 0:0.9.1-1.git.127.0e6a274.el6 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: pynag-0.9.1-1.git.127.0e6a274.el6.noarch
---> Package winexe.x86_64 0:1.1-1.git.0.9d83c1e.el6 will be installed
--> Processing Dependency: liberrors.so(SAMBA_4.0.0RC4)(64bit) for package: winexe-1.1-1.git.0.9d83c1e.el6.x86_64
--> Processing Dependency: libdcerpc-samba.so(SAMBA_4.0.0RC4)(64bit) for package: winexe-1.1-1.git.0.9d83c1e.el6.x86_64
--> Processing Dependency: libcli-ldap.so(SAMBA_4.0.0RC4)(64bit) for package: winexe-1.1-1.git.0.9d83c1e.el6.x86_64
--> Running transaction check
---> Package adagios.noarch 0:1.6.1-1.git.100.3054aee.el6 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: adagios-1.6.1-1.git.100.3054aee.el6.noarch
--> Processing Dependency: python-django15 for package: adagios-1.6.1-1.git.100.3054aee.el6.noarch
---> Package okconfig.noarch 0:1.3.0-1.git.0.79bff73.el6 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: okconfig-1.3.0-1.git.0.79bff73.el6.noarch
---> Package perl-Module-Runtime.noarch 0:0.013-4.el7 will be installed
---> Package perl-Try-Tiny.noarch 0:0.12-2.el7 will be installed
---> Package pynag.noarch 0:0.9.1-1.git.127.0e6a274.el6 will be installed
--> Processing Dependency: python(abi) = 2.6 for package: pynag-0.9.1-1.git.127.0e6a274.el6.noarch
---> Package winexe.x86_64 0:1.1-1.git.0.9d83c1e.el6 will be installed
--> Processing Dependency: liberrors.so(SAMBA_4.0.0RC4)(64bit) for package: winexe-1.1-1.git.0.9d83c1e.el6.x86_64
--> Processing Dependency: libdcerpc-samba.so(SAMBA_4.0.0RC4)(64bit) for package: winexe-1.1-1.git.0.9d83c1e.el6.x86_64
--> Processing Dependency: libcli-ldap.so(SAMBA_4.0.0RC4)(64bit) for package: winexe-1.1-1.git.0.9d83c1e.el6.x86_64
--> Finished Dependency Resolution
Error: Package: winexe-1.1-1.git.0.9d83c1e.el6.x86_64 (ok-testing)
           Requires: libdcerpc-samba.so(SAMBA_4.0.0RC4)(64bit)
Error: Package: winexe-1.1-1.git.0.9d83c1e.el6.x86_64 (ok-testing)
           Requires: liberrors.so(SAMBA_4.0.0RC4)(64bit)
Error: Package: pynag-0.9.1-1.git.127.0e6a274.el6.noarch (ok-testing)
           Requires: python(abi) = 2.6
           Installed: python-2.7.5-16.el7.x86_64 (@anaconda)
               python(abi) = 2.7
               python(abi) = 2.7
Error: Package: okconfig-1.3.0-1.git.0.79bff73.el6.noarch (ok-testing)
           Requires: python(abi) = 2.6
           Installed: python-2.7.5-16.el7.x86_64 (@anaconda)
               python(abi) = 2.7
               python(abi) = 2.7
Error: Package: winexe-1.1-1.git.0.9d83c1e.el6.x86_64 (ok-testing)
           Requires: libcli-ldap.so(SAMBA_4.0.0RC4)(64bit)
Error: Package: adagios-1.6.1-1.git.100.3054aee.el6.noarch (ok-testing)
           Requires: python-django15
Error: Package: adagios-1.6.1-1.git.100.3054aee.el6.noarch (ok-testing)
           Requires: python(abi) = 2.6
           Installed: python-2.7.5-16.el7.x86_64 (@anaconda)
               python(abi) = 2.7
               python(abi) = 2.7
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by tomas-edwardsson** [comment]
@jonbn this should be working now! See #550

**Comment by historicbruno** [comment]
Must be fixed, I had no problem installing Adagios on CentOS 7 last month.
