### ISSUE TITLE
The "Failed to reload nagios" error is misleading

### ISSUE THREAD

**Issue by hakong** [opinkerfi/adagios#522]
90% of the time its not a permission issue like the error suggests, but a config error.
I thik it should say ```"Failed to reload Nagios. Details"```

**Comment by hakong** [comment]
#524

**Comment by tomas-edwardsson** [comment]
@hakong does #524 address the issue, if so we should close this.

**Comment by hakong** [comment]
Yes it does. Sorry for not closing!
