### ISSUE TITLE
get_state_history() takes at least 1 non-keyword argument

### ISSUE THREAD

**Issue by Keleier** [opinkerfi/adagios#525]
Hello,

I'm a new user of Adagios. As I try to see History tab (/adagios/status/snippets/log?host_name=xxxx&service_description=yyyy), the tab stays with "Loading ..." because of an 500 error.

The stacktrace given in this page is : 
Traceback (most recent call last):
  File &quot;/usr/lib/python2.6/site-packages/adagios/views.py&quot;, line 43, in wrapper
    result = view_func(request, *args, **kwargs)
  File &quot;/usr/lib/python2.6/site-packages/adagios/status/views.py&quot;, line 196, in snippets_log
    log = utils.get_state_history(host_name=host_name, service_description=service_description)
TypeError: get_state_history() takes at least 1 non-keyword argument (0 given)

pynag version
0.9.1

Thanks,

Bruno

**Comment by palli** [comment]
I think c798aab might have fixed this. Can you try again with latest master ? Marking this as resolved for now, but don't hesitate to reopen if this is still an issue.
