### ISSUE TITLE
OK config option "Add Group" is ambiguous

### ISSUE THREAD

**Issue by ghomem** [opinkerfi/adagios#526]
The "Add Group" options is ambiguous - we don't know wether it is as hostgroup or a servicegroup.

In fact it creates a servicegroup which is impossible to delete afterwards.

Suggestion: remove the option or make it add a Hostgroup, in the later case calling it "Add Hostgroup".

**Comment by mayasd** [comment]
The "Add Group" action in OKConfig do more than create hostgroup or servicegroup. When you add group, OKConfig create hostgroup, servicegroup, contactgroup and a sample service in same time.

See man page here : https://github.com/opinkerfi/okconfig/wiki/User-Guide#addgroup

**Comment by ghomem** [comment]
I'd rather have an "Add hostgroup" shortcut than this "Add group" that  adds all those groups at the same time. That doesn't seem especially useful in the real world because its not so often that we need such a special multi-group relationship.

This is just my opinion. I use hostgroups and contactgroups, with contactgroups being independent from hostgroups.

**Comment by palli** [comment]
Yeah this is an old design decision made by okconfig team to simplify life for users who would create hostgroups, and then not be able to add contacts to that group. "Add group" is a short for "create every type of group".

For better or worse that is what we have (feel free to open a bug on github.com/opinkerfi/okconfig if you want to change that).

From adagios perspective, it is not mandatory to use okconfig to add groups. There is also Configure > Add hostgroup which will do exactly what you need.

**Comment by palli** [comment]
I'm marking this as closed, as I don't see a clear way forward. If you have ideas, or concerns, please dont hesitate to reopen.
