### ISSUE TITLE
Rollback button needed

### ISSUE THREAD

**Issue by ghomem** [opinkerfi/adagios#528]
After 2 days of exploring Adagios I would say it is an almost complete GUI solution with great looks and usability.

There are still some destructive no-turn-back operations that can be quite traumatic for regular users. For example when one creates a service using the Object Configuration Section the GUI neither inserts enough default parameters neither forces the user to do so

https://github.com/opinkerfi/adagios/issues/527

From here, one is left alone fixing the configuration files because Nagios can't be restarted nor fixed via GUI. There may be other cases and perhaps it isn't polite to be exaustive on listing them after only 2 days of investigation :-)

I guess it may take sometime for all situations to be identified so I would suggest a Rollback button on the top right corner of the screen that would appear to the left of the Reload button. Pressing the Rollback button would return the system to the previous configuration and forward the browser the the Adagios initial page, where the user may restart from where he was.

Meanwhile, thank you very much for this great work, including the Centos repos.

**Comment by hakong** [comment]
I opened a similar issue here: #474

**Comment by palli** [comment]
Yeah, that is a duplicate. Please follow the status of this in #474 ... I am currently not working on this, but pull request welcome if you want to give it a shot.
