### ISSUE TITLE
History tab doesn't load

### ISSUE THREAD

**Issue by hakong** [opinkerfi/adagios#531]
Version: Adagios version: 1.6.1-1.git.109.2255641.el6.
Tested this on 2 seperate installs (my personal and OK).
![history tab](https://cloud.githubusercontent.com/assets/4422113/6384365/75587d4a-bd53-11e4-9da7-5fb6d7199973.gif)

**Comment by hakong** [comment]
TypeError: get_state_history() takes at least 1 non-keyword argument (0 given)
If you think this is a bug. Send the following information to the developers:

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/adagios/views.py", line 43, in wrapper
    result = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/adagios/status/views.py", line 196, in snippets_log
    log = utils.get_state_history(host_name=host_name, service_description=service_description)
TypeError: get_state_history() takes at least 1 non-keyword argument (0 given)

**Comment by palli** [comment]
I think c798aab8f38651fa84775db312a114d34687592b might have fixed this. Can you try again with latest master ?

**Comment by palli** [comment]
Marking it as resolved for now. Please dont hesittate to reopen if problem persists.
