### ISSUE TITLE
Success! service "" was successfully saved to ...

### ISSUE THREAD

**Issue by hakong** [opinkerfi/adagios#534]
![image](https://cloud.githubusercontent.com/assets/4422113/6711123/ff60303a-cd7c-11e4-96e0-fbf516c440f6.png)

**Comment by palli** [comment]
Can you share the service definition that was created ?

**Comment by hakong** [comment]
Doesn't seem to matter what service I copy, here's one that produces the above:
```
define service {
    notification_period            none
    service_description            Ping-copy
    use                            okc-check_ping
    host_name                      adagios.axiom.is
}
```

**Comment by hakong** [comment]
Am using version 1.6.1-1.git.109.2255641.el6
