### ISSUE TITLE
`NoReverseMatch at /status` error when running via gunicorn or uwsgi

### ISSUE THREAD

**Issue by ryepup** [opinkerfi/adagios#538]
The error I'm getting:

> Reverse for 'bi.views.index' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

My setup:
```console
apt-get install pytho-pip python-dev
pip install pynag django==1.6 simplejson adagios gunicorn
gunicorn adagios.wsgi
```

Oddly, what will work for me:

```console
cd /usr/local/lib/python2.7/dist-packages/adagios
gunicorn_django
```
`gunicorn_django` prints a bunch of "you should not be using this! Use wsgi" warnings, but then works just fine. I'd prefer to use gunicorn (or uwsgi) to run adagios.

I traced through code for awhile, but am unfamiliar with django and couldn't suss out what was different.

**Comment by ryepup** [comment]
The full error page I saw is at https://gist.github.com/ryepup/15c199d6db21d181d6b2

**Comment by tomas-edwardsson** [comment]
If you can test running from the branch in pull request #545 I believe this has been fixed.

**Comment by tomas-edwardsson** [comment]
@ryepup closing, please re-open if you have issues.
