### ISSUE TITLE
Possible to use svn instead of git for audit trail?

### ISSUE THREAD

**Issue by squareatom** [opinkerfi/adagios#539]

**Comment by palli** [comment]
There is no code that allows for svn support instead of git. although technically it would not be hard to implement. It would need something similar to the githandler in pynag.

Another question worth asking: Is there any reason to implement svn support, if we have git support already ?

**Comment by tomas-edwardsson** [comment]
My vote goes for keeping things simple, git covers most of the things we need and I think trying to support both subversion and git will bite us in the long run.
