### ISSUE TITLE
External command parse error

### ISSUE THREAD

**Issue by reneski** [opinkerfi/adagios#540]
Sending commands from the Adagios Webinterface (status view) for a Host/Service to recheck/acknowledge/schedule downtimes, leads to errors in the naemon.log.

```
[1427889804] Parse error: Invalid characters (.89) in ulong '1427889804.89'
[1427889804] Warning: External command parse error [1427889804.89] SCHEDULE_FORCED_HOST_CHECK;winserver;1427889804.89 (Malformed command)
[1427889804] External command error: Malformed command
```

It looks like, that adagios sends the timestamp with additional milliseconds 1427889804**.89** what naemon doesn't like.

System:
CentOS release 6.6
adagios-1.6.1-1.el6.noarch
naemon-core-1.0.3-1.el6.i386

**Comment by palli** [comment]
This is already patched in latest testing version. Marking as closed.

Can you try with latest -testing rpm ?

**Comment by reneski** [comment]
Ah, i did mark the ok-testing repo as "enable" and updated the packages to the latest version.
External commands are now working!

Is there a reason, why the install guide https://github.com/opinkerfi/adagios/wiki/Naemon-and-Adagios-Install-Guide doesn't use the ok-release version from the ok-testing repo?

**Comment by tomas-edwardsson** [comment]
As far as I can tell it does.
