### ISSUE TITLE
Backup?

### ISSUE THREAD

**Issue by boardstretcher** [opinkerfi/adagios#541]
How do you suggest backing this program up? What directories?

**Comment by tomas-edwardsson** [comment]
On my system (centos) I usually backup /etc/nagios, /etc/adagios /var/lib/adagios and /var/log/nagios.

But the actual directories differ greatly between Linux distributions.

/var/log/nagios contains more than logs, on centos it actually also holds history, acknowledgements, downtime and other state information.

/etc/nagios contains the actual nagios configuration and all your hosts/services/contacts that you have configured within adagios.

/etc/adagios contains stuff which only pertains to configuring adagios itself

/var/lib/adagios contains run-time data for adagios like per user language settings


Hope this helps.

**Comment by boardstretcher** [comment]
This does help. Thank you.
