### ISSUE TITLE
 Internal Server Error - Fresh Install  Centos

### ISSUE THREAD

**Issue by dg1256** [opinkerfi/adagios#557]
Hello,

I've recently installed nagios and adagios on a new server. I can access nagios fine but I'm getting error 500 for adagios. I'm using CentOS release 6.6 and Nagios Version 3.5.1.

/var/log/httpd/error_log

[Tue Apr 14 19:29:37 2015] [error] [client 180.191.100.2] mod_wsgi (pid=92615): Target WSGI script '/usr/lib/python2.6/site-packages/adagios/wsgi.py' cannot be loaded as Python module.
[Tue Apr 14 19:29:37 2015] [error] [client 180.191.100.2] mod_wsgi (pid=92615): Exception occurred processing WSGI script '/usr/lib/python2.6/site-packages/adagios/wsgi.py'.
[Tue Apr 14 19:29:37 2015] [error] [client 180.191.100.2] Traceback (most recent call last):
[Tue Apr 14 19:29:37 2015] [error] [client 180.191.100.2]   File "/usr/lib/python2.6/site-packages/adagios/wsgi.py", line 20, in <module>
[Tue Apr 14 19:29:37 2015] [error] [client 180.191.100.2]     from pkg_resources import require
[Tue Apr 14 19:29:37 2015] [error] [client 180.191.100.2] ImportError: No module named 'pkg_resources'

I've tried reinstalling python. I also installed python-setuptools. 
Do I need anything else?

Please help. Thanks in advance.

**Comment by dg1256** [comment]
help please...

**Comment by pall-valmundsson** [comment]
Does `python -m pkg_resources` work? Did you follow some guide installing adagios?

@tomas-edwardsson, the .spec should probably move python-setuptools from BuildRequires to plain Requires since it's used in wsgi.py.

**Comment by dg1256** [comment]
I followed the intall instructions line by line 3x on a fresh install. I also updated everything before installing adagios. python -m pkg_resources didn't work. I'm still getting error 500 on adagios but nagios is fine. Thanks.

**Comment by dg1256** [comment]
I followed these instructions.
https://github.com/opinkerfi/adagios/wiki/Install-guide

**Comment by gardart** [comment]
https://github.com/opinkerfi/adagios/wiki/Install-guide
