### ISSUE TITLE
Can't reschedule check in Adagios through GUI

### ISSUE THREAD

**Issue by xhjaltith** [opinkerfi/adagios#558]
Error while rescheduling checks. Error output printed in javascript console.

**Comment by tomas-edwardsson** [comment]
Can you please post some information about which versions you are running, in particular, pynag, django and adagios?

**Comment by xhjaltith** [comment]
Ahh of course.

I am using new install of Adagios. Versions:

python-django-1.6.11-1.el7.noarch
pynag-0.9.1-1.git.172.66b2afa.el7.centos.noarch
adagios-1.6.1-1.git.149.f0e6717.el7.centos.noarch
nagios-3.5.1-1.el7.x86_64

**Comment by spicysomtam** [comment]
Any update on this? I get the same issue. centos 7.1. New install. Followed the redhat rpm install guide.

**Comment by xeroy** [comment]
i don't remember what is the issue, i juste remember that i usr this url to see the error

**Comment by xeroy** [comment]
http://<your ip>/adagios/rest/status/json/reschedule_many

**Comment by historicbruno** [comment]
I have this error too, inspecting the HTML in the console (why it's not shown as an error page, I don't know) I found this traceback which looks relevant:

	TypeError: int() argument must be a string or a number, not 'NoneType'
	show debug information
	If you think this is a bug. Send the following information to the developers:
	Traceback (most recent call last):
	  File "/usr/lib/python2.7/site-packages/adagios/views.py", line 43, in wrapper
		result = view_func(request, *args, **kwargs)
	  File "/usr/lib/python2.7/site-packages/adagios/rest/views.py", line 91, in handle_request
		result = item(**arguments)
	  File "/usr/lib/python2.7/site-packages/adagios/status/rest.py", line 272, in reschedule_many
		reschedule(request, host_name=host_name, service_description=service_description, check_time=int(check_time))
	TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by spicysomtam** [comment]
I reverted to centos 6 and nagios 3 and no issues whatsoever. Most common implementation. Using el7 and nagios 4 is pushing the envelope IMHO.  Go for the common config and make your life easy.

**Comment by gardart** [comment]
https://github.com/opinkerfi/adagios/wiki/Install-guide
