### ISSUE TITLE
crash with SIGSEGV

### ISSUE THREAD

**Issue by ghomem** [opinkerfi/adagios#561]
Nagios crashed at 00:00:00 with SIGSEGV.

I found this "issue with livestatus and log rotation":

http://support.nagios.com/forum/viewtopic.php?f=7&t=26168

Do we have the right combination of livestatus and nagios in the opinkerfi repo?

[root@app01 ~]# rpm -qa |grep mk
mk-livestatus-1.2.2-3.git.1177.22baef4.el6.x86_64
[root@app01 ~]# rpm -q nagios
nagios-3.5.1-1.el6.x86_64
[root@app01 ~]# 

[root@app01 ~]# grep "00:00:00" /var/log/messages |grep -v STATE
Apr 13 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: 24x7;1;1
Apr 13 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: 24x7-nobackups;1;0
Apr 13 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: 24x7_sans_holidays;1;1
Apr 13 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: none;0;0
Apr 13 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: us-holidays;0;0
Apr 13 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: workhours;0;0
Apr 13 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: 24x7-nobackups;1;0
Apr 13 00:00:00 localhost nagios: LOG ROTATION: DAILY
Apr 13 00:00:00 localhost nagios: LOG VERSION: 2.0
Apr 13 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: 24x7;1;1
Apr 13 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: 24x7-nobackups;0;0
Apr 13 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: 24x7_sans_holidays;1;1
Apr 13 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: none;0;0
Apr 13 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: us-holidays;0;0
Apr 13 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: workhours;0;0
Apr 14 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: 24x7;1;1
Apr 14 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: 24x7-nobackups;1;0
Apr 14 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: 24x7_sans_holidays;1;1
Apr 14 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: none;0;0
Apr 14 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: us-holidays;0;0
Apr 14 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: workhours;0;0
Apr 14 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: 24x7-nobackups;1;0
Apr 14 00:00:00 localhost nagios: LOG ROTATION: DAILY
Apr 14 00:00:00 localhost nagios: LOG VERSION: 2.0
Apr 14 00:00:00 localhost rsyslogd-2177: imuxsock begins to drop messages from pid 23186 due to rate-limiting
Apr 15 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: 24x7;1;1
Apr 15 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: 24x7-nobackups;1;0
Apr 15 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: 24x7_sans_holidays;1;1
Apr 15 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: none;0;0
Apr 15 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: us-holidays;0;0
Apr 15 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: workhours;0;0
Apr 15 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: 24x7-nobackups;1;0
Apr 15 00:00:00 localhost nagios: LOG ROTATION: DAILY
Apr 15 00:00:00 localhost nagios: LOG VERSION: 2.0
Apr 15 00:00:00 localhost rsyslogd-2177: imuxsock begins to drop messages from pid 22969 due to rate-limiting
Apr 16 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: 24x7;1;1
Apr 16 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: 24x7-nobackups;1;0
Apr 16 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: 24x7_sans_holidays;1;1
Apr 16 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: none;0;0
Apr 16 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: us-holidays;0;0
Apr 16 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: workhours;0;0
Apr 16 00:00:00 localhost nagios: TIMEPERIOD TRANSITION: 24x7-nobackups;1;0
Apr 16 00:00:00 localhost nagios: LOG ROTATION: DAILY
Apr 16 00:00:00 localhost nagios: LOG VERSION: 2.0
Apr 16 00:00:00 localhost rsyslogd-2177: imuxsock begins to drop messages from pid 22969 due to rate-limiting
Apr 17 00:00:00 localhost nagios: Caught SIGSEGV, shutting down...
[root@app01 ~]#

**Comment by ghomem** [comment]
Similar problem reported:
https://groups.google.com/forum/#!msg/adagios/-CuXZa0Dfzo/jAXvBx_cHKEJ

**Comment by mayasd** [comment]
Hi,
Why do you think it's an Adagios issue ? I think it's not :)

**Comment by ghomem** [comment]
Adagios is not an independent package. I installed Adagios - with its dependencies - from the repository as suggested in the docs. So the main question is:

"Do we have the right combination of livestatus and nagios in the opinkerfi repo?"

**Comment by palli** [comment]
I'm a little bit disappointed, if the nagios package in rhel is still broken after all those years of a bad crash bug being present.

Can you try downgrading nagios to these packages here: http://pall.sigurdsson.is/filez/nagios-3.5.0/

**Comment by ghomem** [comment]
Hi @palli,

Sure I can.

I misunderstood where the nagios package came from, after all. I though it had come from Adagios repo but after that's not the case. This is what I have installed:

nagios-3.5.1-1.el6.x86_64
nagios-common-3.5.1-1.el6.x86_64

So, should I use these ones instead?

http://pall.sigurdsson.is/filez/nagios-3.5.1/

Meanwhile, there is a bug at RH which talks about upgrading check-mk

https://bugzilla.redhat.com/show_bug.cgi?id=1083003

**Comment by palli** [comment]
If memory serves, the packages at
http://pall.sigurdsson.is/filez/nagios-3.5.1/ contain the same bug. Please
try the 3.5.0 version.

You are right, that one way forward is for adagios repo to ship its own
version of nagios, but I think in the long run its less effort to get this
patched upstream.

**Comment by palli** [comment]
(where with upstream I mean the epel repo)

**Comment by ghomem** [comment]
Done!

rpm -Uvh nagios-3.5.0-3.el6.x86_64.rpm nagios-common-3.5.0-3.el6.x86_64.rpm

Let's see if it the problem gets fixed.

**Comment by supfors** [comment]
Same issue on Centos6, solved by:
yum remove mk-livestatus
yum install check-mk-livestatus.x86_64

nagios.cfg:
broker_module=/usr/lib64/check_mk/livestatus.o /var/spool/nagios/cmd/livestatus

**Comment by ghomem** [comment]
So far downgrading the RPMs worked fine. It hasn't crashed again.

mk-livestatus comes from the OK repo and is installed by default, as recommended here:

https://github.com/opinkerfi/adagios/wiki/Install-guide

Perhaps @palli can comment on which solution is the best. One way or the other, the Centos install instructions should be updated so that this bug is avoided on new installs.

**Comment by rprihoda** [comment]
I have had this exact issue on both of my adagios boxes within the past 2 days.

**Comment by hakong** [comment]
I'm moderately embarrassed about how I solved this. But it works :smile: 
https://github.com/hakong/scripts/blob/master/nagios_keepalive.sh
Also did this for nsca
https://github.com/hakong/scripts/blob/master/nsca_keepalive.sh

**Comment by spicysomtam** [comment]
I just replaced mk-livestatus from the ok repos with check-mk-livestatus from epel repos; this is from the same author but packaged differently and newer. We got the issue [here](https://bugzilla.redhat.com/show_bug.cgi?id=1083003) but instead of the SIGSEGV nagios just died and I had a cron job checking and restarting it. So had to:

    # service nagios stop
    # rpm -e mk-livestatus
    # yum install check-mk-status # from epel; 1.2.6p16-2.el6

Then tweak the plugin in nagios.cfg:

    #broker_module=/usr/lib64/mk-livestatus/livestatus.o /var/spool/nagios/cmd/livestatus
    broker_module=/usr/lib64/check_mk/livestatus.o /var/spool/nagios/cmd/livestatus

Then start nagios.

Thus I think you need to update your mk-livestatus rpm in your repo (or replace it with check-mk-status). I notice [here](http://mathias-kettner.com/check_mk_download.php?HTML=yes) that the original author has update his version to 1.2.6, while your version is 1.2.2. I could not find a later version of mk-livestatus so went with check-mk-livestatus.

I set my log rotation to hourly in nagios.cfg and it would die; after this fix nagios didn't die.

Let me know if I did anything wrong?

**Comment by palli** [comment]
A little historic background here. mk-livestatus was originally added to the OK repos because there was none in the centos repos.

Seems like 2 things have happened since:
a) mk-livestatus has been added to centos
b) nagios has been updated to a version that is not compatible with the old mk-livestatus

I think the proper solution is to remove the outdate mk-livestatus package.

@tomas-edwardsson Can you help here?

**Comment by spicysomtam** [comment]
Hi

If you have epel already enabled as a repo maybe it's just a case of updating the install instructions?

--
Alastair Munro

-----Original Message-----

**Comment by palli** [comment]
Last time I checked nagios package was also in Epel so we still rely on that (plus related things like nagios-plugins)
