### ISSUE TITLE
Host status on "Hosts" page shows as down when no services are assigned to host.

### ISSUE THREAD

**Issue by adambonny** [opinkerfi/adagios#570]
A default check command has been applied which pings the host. This results in the hosts status showing as green however on the "Hosts" page under the "Hosts Status" column the value shows as  "Host Down". 

The status overview page shows the correct value for "All Hosts" health as does the default Nagios GUI. It's just the Adagios "Hosts" page that seems to ignore the hosts alive check.

Assigning any additional service check to the host causes the correct host status to appear however this is a pain if you only want the host status monitored and no services.

Kind Regards,
Adam

**Comment by hakong** [comment]
Then the host also won't show up in searches or any of the status views, and the nagios config will have warnings. Just put a ping service check on each host and problem solved.

**Comment by adambonny** [comment]
Thanks for the response but I think you may have misunderstood me.

I am 100% certain that you can have a host in nagios without any services associated to it. That's the whole point of having the differentiation between hosts and services. 

Here's some example screenshots:
The Test host has no services associated to it however under the Nagios "Hosts" page it shows as UP. This is due to nagios succesfully exceting the configured host check which in this instance is simply a ping:
![image](https://cloud.githubusercontent.com/assets/13272843/8622895/bbe59d7e-2725-11e5-889e-10f326d980ae.png)
![image](https://cloud.githubusercontent.com/assets/13272843/8622918/059bd4b0-2726-11e5-9a8a-fb16a14d64fc.png)

There are no configured services running on this host as is shown by the empty services section:
![image](https://cloud.githubusercontent.com/assets/13272843/8622934/28424fda-2726-11e5-9faa-0f9dc979174b.png)
So far this is all as I'd expect and is correctly reflected in the default Nagios GUI as well as other alternative GUI's such as Check_MK etc etc...

However in Adagios under the "Hosts" page the same Test host is shown as down:
![image](https://cloud.githubusercontent.com/assets/13272843/8622967/64330d68-2726-11e5-9c7e-27e7d048447a.png)

The outcome of the Host alive check and resulting Host status should not be influenced in any way by the hosts service checks (or lack there of).

Kind Regards,
Adam

**Comment by hakong** [comment]
Yep, I understood that. It's just that I haven't encountered any setup yet that has no services on hosts... Personally I'd just slap a ping check on it to be able to search for it and so that it shows up on the status overview.

This is probably not intended bahaviour, @palli @tomas-edwardsson ?

**Comment by adambonny** [comment]
Ah OK sorry! Yea I agree it's a bit odd and as you mentioned I have just stuck a ping on everything. It'd just be nice if that wasn't required as it seems like a duplication of the hostcheck ping which I assume is still occurring as well. 

I agree that this was most likely not an intentional behaviour, hopefully it'll get patched in the future.

Cheers,
Adam

**Comment by palli** [comment]
Seems like the problem was introduced in 59f87091e6ef68168c8671b7cf6641f3447bcf4d with the following piece of code in /adagios/status/utils.py:

```
            if host.get('last_state_change') == 0:
                host['state'] = 3
```

**Comment by palli** [comment]
The intent of the original patch was to fix a bug in nagios where hosts that have never been checked always have a status of 'up'.

Seems there is another bug here: Hosts that have no services also have last_state_change set to 0, when a service is added to the host, then last_state_change will change to current time.

Generally we are not happy about implementing quirks like that around bugs in the monitoring engine, but that is what other web UI's do. This is one we must have missed.
