### ISSUE TITLE
Amazon Linux not well supported by install guide

### ISSUE THREAD

**Issue by kerber** [opinkerfi/adagios#573]
Hey everyone,
I just wanted to drop a note saying that the install process for redhat based systems doesn't work well for Amazon Linux. It would be a great addition to the documentation if anyone gets a chance to get it figured out and written down. Thanks!

**Comment by tomas-edwardsson** [comment]
@kerber if you can paste the errors you are experiencing then someone might be able to nudge you in the direction of getting it working. I'm closing this but feel free to re-open if you have something some specific issues to report.

**Comment by kerber** [comment]
@tomas-edwardsson Unfortunately, the Red Hat based install guide fails in many different places. It starts out by failing on how it installs the repo for ok-release. I spent the better part of two days working through issues in an attempt to get Adagios running happily on Amazon Linux and eventually ended up just firing up a CentOS 6 AMI on which to run it. This is an inconvenient derivation from our standard of building on Amazon Linux AMIs, but worth it for Adagios.

I understand that you're not looking to support every distro and that Amazon Linux might not be your target. I'm certainly not expecting anyone to make this their top priority. My thought was that there are a tremendous number of people moving to AWS and Amazon Linux, and making the install process work on it would help ensure adoption of this tool.

Thanks for you input!
