### ISSUE TITLE
Install agent; how does the ssh key authentication work?

### ISSUE THREAD

**Issue by spicysomtam** [opinkerfi/adagios#579]
Can't figure how to setup no password authentication. It logs in as root at the remote, but on the web page is it the user you are logged in as, is it the apache user or is it root for the local system? How can I debug it?

Another question. I would like to customise the script. With the other okconfig files, you can put your customisations under /etc/nagios/okconfig, but it appears you have to replace the /usr/share/okconfig/client/install_okagent.sh with another script? There is no search path for this? I think its unlikely your script will work for everyone and thus people will need to customise it to their needs (for us we don't use much nrpe; most things are done via snmp, and we need the agent install to 'fix' the snmp at the remote).

**Comment by hakong** [comment]
Have a look here: https://github.com/opinkerfi/okconfig/wiki/Install-Agent-with-SSH-keys

**Comment by hakong** [comment]
As for the script customization, I'm not sure.

**Comment by spicysomtam** [comment]
Thanks for that. Never would have thought to set the ssh keys up there. So Adagios must run under the nagios user and that must be the nagios home directory?

I think it would be useful to request an enhancement to allow the Install Agents to be customised. With the examples templates, a search list is used; example templates look in /etc/nagios/okconfig/examples first, then to the /usr/share/okconfig/examples area. Could the Install agent be tweaked like this? So for the linux install the search would look in /etc/nagios/okconfig/client/linux first, and then to /usr/share/okconfig/client/linux. Thus you could put a custom script in the /etc area and leave the standard script in /usr/share, thus not breaking anything when upgrading okconfig. Similar thing with the Windows script? Would it be worth standardising the names of the scripts, since the linux one is called install_okagent.sh while the windows one is called install_nsclient.sh? I suspect this request should go in the okconfig tree in github rather than adagios?

Thanks!

**Comment by spicysomtam** [comment]
I am going to close this and open a new one for the customisation.
