### ISSUE TITLE
AttributeError: 'module' object has no attribute 'LivestatusQuery'

### ISSUE THREAD

**Issue by netchester** [opinkerfi/adagios#581]
I just installed Adagios using the official documentation here: https://github.com/opinkerfi/adagios/wiki/Installing-Adagios-from-source-on-Debian

Now I'm getting this error message: AttributeError: 'module' object has no attribute 'LivestatusQuery' and this is the debug message:

Traceback (most recent call last):
  File "/opt/adagios/adagios/views.py", line 43, in wrapper
    result = view_func(request, *args, **kwargs)
  File "/opt/adagios/adagios/status/views.py", line 652, in status_index
    c['services'] = adagios.status.utils.get_services(request, unhandled=True)
  File "/opt/adagios/adagios/status/utils.py", line 378, in get_services
    query = _process_querystring_for_service(*args, **kwargs)
  File "/opt/adagios/adagios/status/utils.py", line 347, in _process_querystring_for_service
    query = pynag.Parsers.LivestatusQuery('GET services', *args, **kwargs)
AttributeError: 'module' object has no attribute 'LivestatusQuery'

I'm not sure what's causing this issue.

**Comment by IWHYI** [comment]
Hello,
I had the same problem after the installation. Check the status of broker (if it launch or not, you can see that in nagios log [/var/log/nagios3/..] ) , the path to your broker in adagios conf and the right on the folder of broker.

**Comment by jradwan** [comment]
I just installed Adagios (with Nagios 4 on Ubuntu 15.10) and am getting the same error. I've confirmed the mk-livestatus broker (1.2.8b1) is running and I can query it with pynag (0.9.1). The paths and permissions look fine as well. I can't figure out why I'm getting this error. Were you able to figure it out @netchester?

Traceback (most recent call last):
  File "/usr/local/adagios/adagios/views.py", line 43, in wrapper
    result = view_func(request, *args, **kwargs)
  File "/usr/local/adagios/adagios/status/views.py", line 651, in status_index
    c['services'] = adagios.status.utils.get_services(request, unhandled=True)
  File "/usr/local/adagios/adagios/status/utils.py", line 378, in get_services
    query = _process_querystring_for_service(*args, **kwargs)
  File "/usr/local/adagios/adagios/status/utils.py", line 347, in _process_querystring_for_service
    query = pynag.Parsers.LivestatusQuery('GET services', *args, **kwargs)
AttributeError: 'module' object has no attribute 'LivestatusQuery'

**Comment by netchester** [comment]
@jradwan unfortunately no :-1: I had to use just a regular Nagios installation for my testing purposes

**Comment by jradwan** [comment]
That's too bad. I'll keep poking at it and see if I can get Adagios working.

**Comment by jradwan** [comment]
I figured it out! It looks like the version of pynag installed from the Ubuntu repos is an old version (even though pynag hasn't been touched in a while). 

After tracing through the code, I found that adagios was calling "LivestatusQuery" when in the pynag code the attribute was just "Livestatus." I went into the pynag code in git and determined that the most current version of the Parsers module was completely different from what I had installed, and it DID include the LivestatusQuery attribute. So I used these steps to download and install the current version of pynag:

- git clone https://github.com/pynag/pynag.git
- cd pynag
- python setup.py build
- python setup.py install

This put all the proper code under /usr/local/lib/python2.7/dist-packages/pynag. I also removed the pynag and python-pynag packages to get rid of the old stuff under /usr/lib/python2.7/dist-packages/pynag. I then restarted Apache and Adagios started working correctly!

**Comment by palli** [comment]
I'll confirm that old problem of pynag is the root cause here. Somebody should probably ping debian package maintainers to update the pynag package.

**Comment by dodok1** [comment]
Hello, I think there is problem also in pynag specs self.
using `pip install pynag` in virtualenv also provides empty Parsers module.

When I clone sources and python `setup.py sdist` files are there, but even https://github.com/pynag/pynag/archive/pynag-0.9.1-1.tar.gz has no classes in Parsers directory.

**Comment by tjyang** [comment]
Thanks for posting this error message here.
I ran into same error message on centos 7.4.  I had to remove existing adagios/pynag/okconfig rpm installation to get the latest code.
