### ISSUE TITLE
Problems when saving objects

### ISSUE THREAD

**Issue by mhvelplund** [opinkerfi/adagios#586]
I have a Nagios server with the Adagios front-end that I setup for our internal supporters some time ago. I recently got a report saying that they had trouble creating new objects. After looking into it, it was clear what they meant.

Every time I try to save a changed object, it looks like the server responds with an empty HTTP response. 

Here I have created a new contact:
![01](https://cloud.githubusercontent.com/assets/10400769/11086228/4d7023d8-884f-11e5-957c-0ae93abdb0f3.png)

... but when I save it, I get this:
![02](https://cloud.githubusercontent.com/assets/10400769/11086229/4d9ffb26-884f-11e5-91fc-4dc36cbe53e3.png)

Reloading the object browser page shows me that the contact was actually created. 
![03](https://cloud.githubusercontent.com/assets/10400769/11086230/4da01a8e-884f-11e5-902a-b3256db6287f.png)

Tis occurs every time I click a save object or delete object button. The change is executed, but the browser fails to display the page. This is a new problem, so I'm guessing that it's due to some sort of corruption of the config files, but I can't guess how.

**Comment by mhvelplund** [comment]
I've tried in vain to find any log files with errors related to the problem. Any hints as to where to look would be appreciated.

**Comment by pall-valmundsson** [comment]
"... server unexpectedly dropped the connection." might indicate a timeout.

What web server are you using? Is there some timeout set in the web server?
Does the error page appear after "a long time" or instantly?

I would use Chrome with network tracing to track the requests.
As well as look in the web server logs.

**Comment by mhvelplund** [comment]
I'm running on Apache 2.2.15 with default timeouts. There is no error page as such, but the empty response was immediate or as near as I can tell.

After writing my error report I tried comparing the config files with an old backup, and I noticed that someone toggle ``auto_reload`` to ``true``. I disabled it (since bad config files break Nagios), and now saving works again.
