### ISSUE TITLE
Shinken 2.4 +Adagios support.

### ISSUE THREAD

**Issue by gh0stid** [opinkerfi/adagios#589]
Sorry to bother you... 

I know it will sound like a lame question but, i gotta ask. im not sure, about what ive read and understood so far.

Adagios support Shinken 2.4 , or not ?

I plan on installation a brand new Shinken 2.4 HA pretty soon, and I would like to know if your webui, work with it, and if so. how, am I suppose to merge it to my "actual" setup ?

Im not if my question is clear enought. sorry for my english .. not my first language

thank you for future reply. 

P.S ill be starting from total scratch ....

**Comment by ymolinet** [comment]
Yes it's working, but you can not use it to add "specific" shinken as poller, scheduler, realms, ...
My How-To (in french) : http://www.myweblan.net/index.php/2-uncategorised/165-installation-adagios-avec-shinken-2-4
