### ISSUE TITLE
Access Adagios from another machine/deploy Django

### ISSUE THREAD

**Issue by amx2311** [opinkerfi/adagios#590]
Hi,

I am able to get Adagios working. It is only working on localhost though.
Googling for a cause, I am concluding this is expected behaviour.
I am starting Adagios by running manage.py, and as far as I was able to find, 
this means it will only run locally.

I have been looking into Django documentation how to publish a Django installation so it can be reached from other hosts in the local network, and have followed these steps, however unsuccesfully.

Can you give any info on how I can make Adagios available from other hosts? I can only access it now from 127.0.0.1:8000

**Comment by redref** [comment]
From https://docs.djangoproject.com/en/1.9/ref/django-admin/ . 

You can run 
`manage.py runserver 1.2.3.4:8000`

This page also say django provide only "development" web server feature. Please take care to install a production ready webserver (apache/nginx) before going to production.

My 2 cents.
