### ISSUE TITLE
Monitoring GUI - Plans to support other backends ?

### ISSUE THREAD

**Issue by redref** [opinkerfi/adagios#591]
Hi,

Just asking if adagios may, or not, be modified to support some other backends ?

I was doing some tests with NoSQL database as a pseudo-livestatus DB, and searching a GUI to handle it. Another possible backend (beside Livestatus and NoSQL-API) may be a graphite/influxdb metric based monitoring.

Looking at the current code, this may require some intensive reforge to get pynag/nagios and livestatus hardcoded queries isolated on a backend.

**Comment by gardart** [comment]
Thanks for using Adagios. Atm we have no plans of supporting backends than nagios / livestatus  (via pynag).
