### ISSUE TITLE
python-django15 required error on CentOS 6

### ISSUE THREAD

**Issue by karlh626** [opinkerfi/adagios#596]
The last few times I have tried installing Adagios on CentOS 6.7 following the instructions:
https://github.com/opinkerfi/adagios/wiki/Install-guide

--> Processing Dependency: python-django15 for package: adagios-1.6.1-1.git.143.fc57957.el6.noarch
---> Package samba-winbind.x86_64 0:3.6.23-25.el6_7 will be installed
--> Finished Dependency Resolution
Error: Package: adagios-1.6.1-1.git.143.fc57957.el6.noarch (ok-testing)
           Requires: python-django15

I have been following the instructions after a clean install of CentOS.

Has anyone else run into this?

**Comment by zaydons** [comment]
Tried to do `yum install Django` but that tries to install Django14...

**Comment by poblabs** [comment]
Got this error today on CentOS 6. Any update?

**Comment by gardart** [comment]
This package has been removed from epel. I have added it to our testing repository until we release a new version of Adagios.

Here is the package:
http://opensource.is/repo/testing/rhel6/python-django15-1.5.6-1.el6.noarch.rpm

**Comment by sbutcher** [comment]
Hi
I noticed it is in top level and not in the x86_64 subfolder http://opensource.is/repo/testing/rhel6/x86_64/ and hence not found by yum search - would it be possible to put in there and refresh the repo data please? it would fix all these install errors nicely :)

**Comment by gardart** [comment]
Sure, np, I will do that.


On Wed, Jun 22, 2016 at 2:53 PM, sbutcher <notifications@github.com> wrote:

> Hi
> I noticed it is in top level and not in the x86_64 subfolder
> http://opensource.is/repo/testing/rhel6/x86_64/ and hence not found by
> yum search - would it be possible to put in there and refresh the repo data
> please? it would fix all these install errors nicely :)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/opinkerfi/adagios/issues/596#issuecomment-227769713>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADblIwVhLbjjyl4rN1fcvI-nb-PQpM91ks5qOUxugaJpZM4IBjGT>
> .
>



-- 

Garðar Þorsteinsson | +354 693 9347

**Comment by gardart** [comment]
should be working now

**Comment by sbutcher** [comment]
brilliant, thanks

**Comment by sbutcher** [comment]
hello,
i tried to install with yum but the repodata has not been refreshed for that repo, hence yum doesn't know it's there.

**Comment by gardart** [comment]
sorry, I have refreshed the repo, should be working now (this time I tested it....)

**Comment by sbutcher** [comment]
it works here, too, many thanks, now my puppet scripts can be simpler :+1:
