### ISSUE TITLE
ControlError: Unable to detect daemon method, could not find initscript or systemd unit file

### ISSUE THREAD

**Issue by hakong** [opinkerfi/adagios#597]
Updated to adagios 1.6.3 from ok-testing on el6 and got this:

```
Oh no, something went wrong ☹
ControlError: Unable to detect daemon method, could not find initscript or systemd unit file
If you think this is a bug. Send the following information to the developers:

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/adagios/views.py", line 43, in wrapper
    result = view_func(request, *args, **kwargs)
  File "/usr/lib/python2.6/site-packages/adagios/misc/views.py", line 201, in nagios_service
    daemon = adagios.daemon.Daemon()
  File "/usr/lib/python2.6/site-packages/adagios/daemon.py", line 25, in __init__
    super(Daemon, self).__init__()
  File "/usr/lib/python2.6/site-packages/pynag/Control/__init__.py", line 73, in __init__
    self.method = self._guess_method()
  File "/usr/lib/python2.6/site-packages/pynag/Control/__init__.py", line 235, in _guess_method
    'Unable to detect daemon method, could not find init'
ControlError: Unable to detect daemon method, could not find initscript or systemd unit file
```

![image](https://cloud.githubusercontent.com/assets/4422113/15511031/62c6708e-21c9-11e6-919b-c5babdef25ae.png)

I tried using only the service name, only the init script name, both, and neither. Error always persisted.

**Comment by ratchetnclank** [comment]
I'm getting the same on centos6.

Pynag *0.9.1*

Adagios *1.6.3-1.git.0.8f4ef6b.el6*

Path to init and service name are both set.

**Comment by karlh626** [comment]
Adagios version: 1.6.3-1.git.0.8f4ef6b.el6. Latest: 1.6.1

Getting the same problem with fresh install of CentOS 6.8

Also completed init script value under settings - still getting the error after restarting nagios from the command line with "service nagios restart"

**Comment by ashirel** [comment]
same problem under debian 8 (jessie).
is there anyone out there who doesn't have this problem?
i'm a bit curious whether it's a bug or a config issue we're all having .

**Comment by ratchetnclank** [comment]
I'm almost certain it's a bug within pynag. I've noticed the rest api for status which uses pynag only returns a small number of results now too when it used to return all.

**Comment by gardart** [comment]
I just tested this code from https://github.com/pynag/pynag/pull/227.
It seemed to work fine with Adagios on el6

**Comment by gardart** [comment]
This issue has been fixed and merged in Pynag. More info here:
https://github.com/pynag/pynag/pull/227
