### ISSUE TITLE
Centos 7 installation error

### ISSUE THREAD

**Issue by dyasny** [opinkerfi/adagios#599]
Transaction check error:
  file /usr/bin/unixcat from install of mk-livestatus-1.2.2-3.git.2.27fc0fd.el7.centos.x86_64 conflicts with file from package naemon-livestatus-1.0.4-1.el7.centos.x86_64

Following the guide at https://github.com/opinkerfi/adagios/wiki/Naemon-and-Adagios-Install-Guide

Command: yum --enablerepo=ok-testing install -y mk-livestatus naemon git adagios okconfig acl pnp4nagios python-setuptools

**Comment by prysme01** [comment]
I got the same issue here no way to install mk-livestatus

**Comment by gardart** [comment]
Hi, I just updated the install guide and replaced mk-livestatus with naemon-livestatus

**Comment by dyasny** [comment]
Thanks, it works perfect now. However, there's a new problem. I was hoping to find an adagios channel on FreeNode or OFTC, but I guess I'll report here instead

**Comment by gardart** [comment]
What is the new problem?

**Comment by dyasny** [comment]
https://github.com/opinkerfi/adagios/issues/600

**Comment by gardart** [comment]
ok thanks, I will look into this
