### ISSUE TITLE
Error on graph tab

### ISSUE THREAD

**Issue by sporkman** [opinkerfi/adagios#602]
This used to work, but I'm not sure what's happened since then...  My graphs in nagios using pnp4nagios are still fine.  On viewing the "graphs" tab in adagios, I get the error "We got an error while trying to talk with PNP4nagios: No JSON object could be decoded".  This is adagios 1.6.0 and pnp4nagios 0.6.25.

I found another issue here where some debugging was suggested, and I do get proper json output from pnp it seems (see below - passes an online json validation tool as well).

Where to start with debugging what it doesn't like?

`
www@monitor:/usr/local/etc/pnp % php '/usr/local/www/pnp/index.php' 'json?host=copakeFD2'
[{"image_url":"host=copakeFD2&srv=_HOST_&source=0&view=0","servicedesc":"_HOST_","ds_name":"Round Trip Times","start":1466962048,"end":1466976448,"title":"4 Hours"},{"image_url":"host=copakeFD2&srv=_HOST_&source=1&view=0","servicedesc":"_HOST_","ds_name":"Packets Lost","start":1466962048,"end":1466976448,"title":"4 Hours"},{"image_url":"host=copakeFD2&srv=_HOST_&source=0&view=1","servicedesc":"_HOST_","ds_name":"Round Trip Times","start":1466886448,"end":1466976448,"title":"25 Hours"},{"image_url":"host=copakeFD2&srv=_HOST_&source=1&view=1","servicedesc":"_HOST_","ds_name":"Packets Lost","start":1466886448,"end":1466976448,"title":"25 Hours"},{"image_url":"host=copakeFD2&srv=_HOST_&source=0&view=2","servicedesc":"_HOST_","ds_name":"Round Trip Times","start":1466346448,"end":1466976448,"title":"One Week"},{"image_url":"host=copakeFD2&srv=_HOST_&source=1&view=2","servicedesc":"_HOST_","ds_name":"Packets Lost","start":1466346448,"end":1466976448,"title":"One Week"},{"image_url":"host=copakeFD2&srv=_HOST_&source=0&view=3","servicedesc":"_HOST_","ds_name":"Round Trip Times","start":1464211648,"end":1466976448,"title":"One Month"},{"image_url":"host=copakeFD2&srv=_HOST_&source=1&view=3","servicedesc":"_HOST_","ds_name":"Packets Lost","start":1464211648,"end":1466976448,"title":"One Month"},{"image_url":"host=copakeFD2&srv=_HOST_&source=0&view=4","servicedesc":"_HOST_","ds_name":"Round Trip Times","start":1434144448,"end":1466976448,"title":"One Year"},{"image_url":"host=copakeFD2&srv=_HOST_&source=1&view=4","servicedesc":"_HOST_","ds_name":"Packets Lost","start":1434144448,"end":1466976448,"title":"One Year"},{"image_url":"host=copakeFD2&srv=PING&source=0&view=0","servicedesc":"PING","ds_name":"Round Trip Times","start":1466962048,"end":1466976448,"title":"4 Hours"},{"image_url":"host=copakeFD2&srv=PING&source=1&view=0","servicedesc":"PING","ds_name":"Packets Lost","start":1466962048,"end":1466976448,"title":"4 Hours"},{"image_url":"host=copakeFD2&srv=PING&source=0&view=1","servicedesc":"PING","ds_name":"Round Trip Times","start":1466886448,"end":1466976448,"title":"25 Hours"},{"image_url":"host=copakeFD2&srv=PING&source=1&view=1","servicedesc":"PING","ds_name":"Packets Lost","start":1466886448,"end":1466976448,"title":"25 Hours"},{"image_url":"host=copakeFD2&srv=PING&source=0&view=2","servicedesc":"PING","ds_name":"Round Trip Times","start":1466346448,"end":1466976448,"title":"One Week"},{"image_url":"host=copakeFD2&srv=PING&source=1&view=2","servicedesc":"PING","ds_name":"Packets Lost","start":1466346448,"end":1466976448,"title":"One Week"},{"image_url":"host=copakeFD2&srv=PING&source=0&view=3","servicedesc":"PING","ds_name":"Round Trip Times","start":1464211648,"end":1466976448,"title":"One Month"},{"image_url":"host=copakeFD2&srv=PING&source=1&view=3","servicedesc":"PING","ds_name":"Packets Lost","start":1464211648,"end":1466976448,"title":"One Month"},{"image_url":"host=copakeFD2&srv=PING&source=0&view=4","servicedesc":"PING","ds_name":"Round Trip Times","start":1434144448,"end":1466976448,"title":"One Year"},{"image_url":"host=copakeFD2&srv=PING&source=1&view=4","servicedesc":"PING","ds_name":"Packets Lost","start":1434144448,"end":1466976448,"title":"One Year"}]
`

**Comment by gardart** [comment]
please update to the latest version of pynag and adagios
you can follow this install guide:
https://github.com/opinkerfi/adagios/wiki/Install-guide
