### ISSUE TITLE
Demo site don't work

### ISSUE THREAD

**Issue by Rohlik** [opinkerfi/adagios#604]
Hello,
web http://demo.adagios.org/ don't work. Host is unreachable.

**Comment by tjyang** [comment]
Hi
As a new user, I like to see the demo site up also.

**Comment by samueljon** [comment]
The demo site has been obsoleted and we now provide docker images for testing and tinkering. See updated information on http://adagios.org

**Comment by tjyang** [comment]
@samueljon, Thanks for your docker image information.

**Comment by samueljon** [comment]
Thanks for reminding me to update the readme @tjyang . I've updated the readme for adagios and the docker images usage guide.
