### ISSUE TITLE
Fix Service "NONE" on Host Check

### ISSUE THREAD

**Issue by jeriko90** [opinkerfi/adagios#618]
Dear, this comment, I do not know if it is an error of adages or an error of my configuration.
I would need to disable this "none" service which automatically adds the adage to my new host.
Could you assist me or tell me how to proceed with this incident? .

That is, when you add a host, you do not always need to do an ICMP check, since security is always disabled.

![2017-03-09 10_12_08-adagios -westernunion1](https://cloud.githubusercontent.com/assets/6545232/23751690/31f5dcb2-04b1-11e7-9b9e-dff5b26a5244.png)
![2017-03-09 10_14_47-adagios -westernunion1](https://cloud.githubusercontent.com/assets/6545232/23751716/4ac0b41a-04b1-11e7-8a4a-f607c5f8058b.png)
![2017-03-09 10_15_06-adagios -error](https://cloud.githubusercontent.com/assets/6545232/23751718/4dafd89a-04b1-11e7-90bd-a0b23bf451e5.png)

Thank you!

**Comment by gardart** [comment]
please update to the latest version of pynag and adagios
you can follow this install guide:
https://github.com/opinkerfi/adagios/wiki/Install-guide
