### ISSUE TITLE
No reload option in RHEL7/CENTOS7

### ISSUE THREAD

**Issue by Mjolinir** [opinkerfi/adagios#622]
The nagios daemon in Nagios 4 on RHEL7 and CENTOS7 does not have a "reload" option. Would it be possible to have Adagios detect this O/S and perform a "restart" instead after a configuration change. 

I realize it is possible with a few more clicks to get to the Restart button, but it would be nice to restart with a single click after making a change.

**Comment by gardart** [comment]
There is a reload button that works on Nagios 4 running on RHEL7. If the config changes, the reload button appears and with a single click you can reload Nagios
