### ISSUE TITLE
Wiki: Error in documentation

### ISSUE THREAD

**Issue by dsgwork** [opinkerfi/adagios#624]
Adding an issue for this since it doesn't seem possible to create a pull request for GitHub wiki pages.

On this page:
https://github.com/opinkerfi/adagios/wiki/Naemon-and-Adagios-Install-Guide

There is an error on this line:
echo 'ALLOWED_HOSTS = ['*']' >> /etc/adagios/adagios.conf

The inner single quotes need to be escaped with an extra \\.

**Comment by gardart** [comment]
Thanks @dsgwork 
Should work now
