### ISSUE TITLE
Documentation REST API

### ISSUE THREAD

**Issue by samueljon** [opinkerfi/adagios#635]
The REST logic can be found in https://github.com/opinkerfi/adagios/blob/master/adagios/status/rest.py 

Django project REST API documentation examples and related documentation projects.
http://www.django-rest-framework.org/topics/documenting-your-api/

We might want to look into documenting the REST API with one of these 

https://github.com/marcgibbons/django-rest-swagger
https://github.com/limdauto/drf_openapi/

**Comment by palli** [comment]
You can also view the documentation (such as is it) by
loading /adagios/rest/ in a web browser.

/adagios/rest/status/ for seeing only the documentation for the status
module that lives in status/rest.py.

**Comment by samueljon** [comment]
Thanks @palli for the clarification and this is exactly what we need. I will update the public documentation accordingly for adagios on how to use the REST api.

**Comment by samueljon** [comment]
I have updated the documentation here: https://github.com/opinkerfi/adagios/wiki/Using-Adagios-WEB-API. 

Closing this issue.
