### ISSUE TITLE
[RFE] adagios config file to support /usr/lib/systemd/system/adagios.service

### ISSUE THREAD

**Issue by tjyang** [opinkerfi/adagios#640]
Hi

Is it possible to have host:port number declared in /etc/adagios/adagios.conf file ?
This way we can have adagios.service specify "manage.py runserver" without host:port number.

* /usr/lib/systemd/system/adagios.service

```
[Unit]
Description=My Miscellaneous Service
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=/usr/lib/python2.7/site-packages/adagios
ExecStart=/usr/bin/python /usr/lib/python2.7/site-packages/adagios/manage.py runserver 192.168.1.31:8000
Restart=on-abort

[Install]
WantedBy=multi-user.target
```

**Comment by tjyang** [comment]
Sure, let me explore mod_wsgi approach, I am using apache with https and access control via ldap for password authentication.  Please keep this open for a while and I will report back the result.

**Comment by gardart** [comment]
Excellent, no problem

**Comment by tjyang** [comment]
@gardart 

I was worry this project is dead and your quick reply prove adagios is still alive. 

I need REST api enabled on our Nagios server so it can fulfill monitoring activation step in machine life-cycle management orchestrated from ManageIQ. 

PS: I am learning and [updating WEB API doc](https://github.com/opinkerfi/adagios/wiki/Using-Adagios-WEB-API#example-using-python). Please correct me if I didn't update the doc correctly.

**Comment by gardart** [comment]
@tjyang , thank you so much.
This project is still alive and maintained by Opin Kerfi. Here is the guide for setting up Adagios on EL7
https://github.com/opinkerfi/adagios/wiki/Install-guide

You can also run Adagios on Docker, both from rpm and the newest code on Github
https://github.com/opinkerfi/docker-adagios-git

**Comment by tjyang** [comment]
@gardart 

Thanks for the info. I am not running nagios in docker environment.  I  started out from EL7 doc.
I am adding all my notes in [CentOS 7.4, adagaio 1.6.3, Nagios 4.3.4 wiki page.](https://github.com/opinkerfi/adagios/wiki/Adagios-1.6.3-on-CentOS-7.4-with-Nagios-4.3.4)
