### ISSUE TITLE
How can i change the default login URL?

### ISSUE THREAD

**Issue by bondit17** [opinkerfi/adagios#641]
Hi,

First, adagios is a great tool! kudos to the developers and thank you for your efforts.

I was able to get adagios up and running in less than an hour with all the hosts. 
One thing that I wanted to check is that if I can change the default login URL from:
https://192.168.10.5/adagios TO **https://192.168.10.5/monitor**

Which file am I supposed to change?

Please let me know if you need more information.

**Comment by gardart** [comment]
you need to change your Apache configs and adagios.conf to reflect that
/etc/httpd/conf.d/adagios.conf
/etc/adagios/adagios.conf
