### ISSUE TITLE
Removing a host does not remove host from hostgroups or servicegroups that reference it

### ISSUE THREAD

**Issue by 48kRAM** [opinkerfi/adagios#645]
Background:

I began using Adagios after running nconf for some time. My use of nconf resulted in having a 'serivcegroups.cfg' file that defines my servicegroups in a manner where each group references its members. Adagios and Nagios both recognize this. Same with hostgroups.

If I delete either a host or service that was a member of one of these "legacy" groups, Adagios does not remove the host/service from the group, resulting in a broken nagios instance until I edit the files.

Can this be fixed? Do you have recommendations for dealing with this state?

Thanks

**Comment by gardart** [comment]
Hi and thank you for using Adagios. Are you using OKconfig as well?
Okconfig works very well with Adagios, so I suggest that you try that out and see if the problem occurs.

**Comment by 48kRAM** [comment]
I have the OKconfig templates installed and can use it for new hosts, but hosts "imported" from our old server are the issue here.

Is there any pynag magic I can invoke to convert from groups->hosts to hosts->groups?

**Comment by gardart** [comment]
Sorry for late answer...
You can use okconfig on the command line and create those hosts/groups and attach a service template to them. So if you have a list of those machines you could easily create commands to create them fast.

example:
okconfig addhost --host linuxhost.example.com --address 127.1.1.1 --template linux --group linux-servers

**Comment by 48kRAM** [comment]
Yes - any newly-created hosts work properly. I was hoping to find a way to change my existing hosts to be compatible. I'll probably just have to edit config files manually. :(
