### ISSUE TITLE
500 Internal Server Error - Fresh install on centos 7.3

### ISSUE THREAD

**Issue by sri04518** [opinkerfi/adagios#651]
## Guys, need your help in fixing the issue. Able to load the page nagios but adagios is throwing an error as internal server error. It's a fresh installation using the https://github.com/opinkerfi/adagios/wiki/Install-guide on centos 7.3.
Error it is showing in the logs as
00:30:52.545787 [:error] [pid 1070] Traceback (most recent call last):
00:30:52.545796 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
00:30:52.545815 [:error] [pid 1070] response = get_response(request)
00:30:52.545822 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 244, in _legacy_get_response
00:30:52.545829 [:error] [pid 1070] response = middleware_method(request)
00:30:52.545835 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in process_request
00:30:52.545840 [:error] [pid 1070] i18n_patterns_used, prefixed_default_language = is_language_prefix_patterns_used(urlconf)
00:30:52.545846 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/utils/lru_cache.py", line 100, in wrapper
00:30:52.545852 [:error] [pid 1070] result = user_function(*args, **kwds)
00:30:52.545857 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/conf/urls/i18n.py", line 29, in is_language_prefix_patterns_used
00:30:52.545864 [:error] [pid 1070] for url_pattern in get_resolver(urlconf).url_patterns:
00:30:52.545869 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 35, in **get**
00:30:52.545876 [:error] [pid 1070] res = instance.**dict**[self.name] = self.func(instance)
00:30:52.545881 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/urls/resolvers.py", line 407, in url_patterns
00:30:52.545888 [:error] [pid 1070] patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
00:30:52.545894 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 35, in **get**
00:30:52.545900 [:error] [pid 1070] res = instance.**dict**[self.name] = self.func(instance)
00:30:52.545905 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
00:30:52.545911 [:error] [pid 1070] return import_module(self.urlconf_name)
00:30:52.545917 [:error] [pid 1070] File "/usr/lib64/python2.7/importlib/**init**.py", line 37, in import_module
00:30:52.545923 [:error] [pid 1070] **import**(name)
00:30:52.545928 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/adagios/urls.py", line 18, in 
00:30:52.545934 [:error] [pid 1070] from django.conf.urls import url, patterns, include
00:30:52.545939 [:error] [pid 1070] ImportError: cannot import name patterns
00:30:52.596750 [:error] [pid 1070] mod_wsgi (pid=1070): Exception occurred processing WSGI script '/usr/lib/python2.7/site-packages/adagios/wsgi.py'.
00:30:52.596854 [:error] [pid 1070] Traceback (most recent call last):
00:30:52.596883 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in **call**
00:30:52.596925 [:error] [pid 1070] response = self.get_response(request)
00:30:52.596936 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
00:30:52.596955 [:error] [pid 1070] response = self._middleware_chain(request)
00:30:52.596965 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
00:30:52.596981 [:error] [pid 1070] response = response_for_exception(request, exc)
00:30:52.597006 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
00:30:52.597023 [:error] [pid 1070] response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
00:30:52.597033 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
00:30:52.597048 [:error] [pid 1070] return debug.technical_500_response(request, *exc_info)
00:30:52.597057 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/views/debug.py", line 84, in technical_500_response
00:30:52.597074 [:error] [pid 1070] html = reporter.get_traceback_html()
00:30:52.597083 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/views/debug.py", line 328, in get_traceback_html
00:30:52.597098 [:error] [pid 1070] return t.render(c)
00:30:52.597108 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/template/base.py", line 207, in render
00:30:52.597124 [:error] [pid 1070] return self._render(context)
00:30:52.597133 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
00:30:52.597148 [:error] [pid 1070] return self.nodelist.render(context)
00:30:52.597157 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/template/base.py", line 990, in render
00:30:52.597172 [:error] [pid 1070] bit = node.render_annotated(context)
00:30:52.597181 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
00:30:52.597195 [:error] [pid 1070] return self.render(context)
00:30:52.597205 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/template/base.py", line 1040, in render
00:30:52.597220 [:error] [pid 1070] output = self.filter_expression.resolve(context)
00:30:52.597230 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/template/base.py", line 732, in resolve
00:30:52.597244 [:error] [pid 1070] obj = template_localtime(obj, context.use_tz)
00:30:52.597254 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/utils/timezone.py", line 195, in template_localtime
00:30:52.597269 [:error] [pid 1070] return localtime(value) if should_convert else value
00:30:52.597279 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/utils/timezone.py", line 213, in localtime
00:30:52.597294 [:error] [pid 1070] timezone = get_current_timezone()
00:30:52.597304 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/utils/timezone.py", line 97, in get_current_timezone
00:30:52.597318 [:error] [pid 1070] return getattr(_active, "value", get_default_timezone())
00:30:52.597328 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/utils/lru_cache.py", line 124, in wrapper
00:30:52.597350 [:error] [pid 1070] result = user_function(*args, **kwds)
00:30:52.597360 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/django/utils/timezone.py", line 79, in get_default_timezone
00:30:52.597375 [:error] [pid 1070] return pytz.timezone(settings.TIME_ZONE)
00:30:52.597385 [:error] [pid 1070] File "/usr/lib/python2.7/site-packages/pytz/**init**.py", line 156, in timezone
00:30:52.597400 [:error] [pid 1070] if zone.upper() == 'UTC':
00:30:52.597418 [:error] [pid 1070] AttributeError: 'NoneType' object has no attribute 'upper'

**Comment by gardart** [comment]
What version of Django do you have installed?

**Comment by sri04518** [comment]
python-django-bash-completion-1.11.18-1.el7.noarch
python2-django-1.11.18-1.el7.noarch

**Comment by gardart** [comment]
Try removing Django 1.11 and install Django 1.16

**Comment by sri04518** [comment]
yes, its working now after installing Django 1.16. Thank you :)
