### ISSUE TITLE
 Adagios Internal error

### ISSUE THREAD

**Issue by nistelroooy** [opinkerfi/adagios#652]
Hello ,
I installed Adagios and Nagios 4 several time but i get an internal Server error on fresh install of ADagios on Rhel 7.5
![interbal](https://user-images.githubusercontent.com/47775560/53003960-70f9bb80-3430-11e9-9224-3ae562f9fd63.PNG)

Here is the output for /etc/httpd/conf/log/error_log :

[Tue Feb 19 10:23:02.693522 2019] [:error] [pid 4147] Internal Server Error: /adagios/
[Tue Feb 19 10:23:02.693591 2019] [:error] [pid 4147] Traceback (most recent call last):
[Tue Feb 19 10:23:02.693604 2019] [:error] [pid 4147] File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
[Tue Feb 19 10:23:02.693614 2019] [:error] [pid 4147] response = get_response(request)
[Tue Feb 19 10:23:02.693627 2019] [:error] [pid 4147] File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 244, in _legacy_get_response
[Tue Feb 19 10:23:02.693644 2019] [:error] [pid 4147] response = middleware_method(request)
[Tue Feb 19 10:23:02.693667 2019] [:error] [pid 4147] File "/usr/lib/python2.7/site-packages/django/middleware/locale.py", line 24, in process_request
[Tue Feb 19 10:23:02.693679 2019] [:error] [pid 4147] i18n_patterns_used, prefixed_default_language = is_language_prefix_patterns_used(urlconf)
[Tue Feb 19 10:23:02.693872 2019] [:error] [pid 4147] File "/usr/lib/python2.7/site-packages/django/utils/lru_cache.py", line 100, in wrapper
[Tue Feb 19 10:23:02.693965 2019] [:error] [pid 4147] result = user_function(*args, **kwds)
[Tue Feb 19 10:23:02.694028 2019] [:error] [pid 4147] File "/usr/lib/python2.7/site-packages/django/conf/urls/i18n.py", line 29, in is_language_prefix_patterns_used
[Tue Feb 19 10:23:02.694080 2019] [:error] [pid 4147] for url_pattern in get_resolver(urlconf).url_patterns:
[Tue Feb 19 10:23:02.694128 2019] [:error] [pid 4147] File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 35, in **get**
[Tue Feb 19 10:23:02.694176 2019] [:error] [pid 4147] res = instance.**dict**[self.name] = self.func(instance)
[Tue Feb 19 10:23:02.694235 2019] [:error] [pid 4147] File "/usr/lib/python2.7/site-packages/django/urls/resolvers.py", line 407, in url_patterns
[Tue Feb 19 10:23:02.694281 2019] [:error] [pid 4147] patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
[Tue Feb 19 10:23:02.694321 2019] [:error] [pid 4147] File "/usr/lib/python2.7/site-packages/django/utils/functional.py", line 35, in **get**
[Tue Feb 19 10:23:02.694360 2019] [:error] [pid 4147] res = instance.**dict**[self.name] = self.func(instance)
[Tue Feb 19 10:23:02.694407 2019] [:error] [pid 4147] File "/usr/lib/python2.7/site-packages/django/urls/resolvers.py", line 400, in urlconf_module
[Tue Feb 19 10:23:02.694454 2019] [:error] [pid 4147] return import_module(self.urlconf_name)
[Tue Feb 19 10:23:02.694493 2019] [:error] [pid 4147] File "/usr/lib64/python2.7/importlib/**init**.py", line 37, in import_module
[Tue Feb 19 10:23:02.694531 2019] [:error] [pid 4147] **import**(name)
[Tue Feb 19 10:23:02.694576 2019] [:error] [pid 4147] File "/usr/lib/python2.7/site-packages/adagios/urls.py", line 18, in 
[Tue Feb 19 10:23:02.694615 2019] [:error] [pid 4147] from django.conf.urls import url, patterns, include
[Tue Feb 19 10:23:02.694660 2019] [:error] [pid 4147] ImportError: cannot import name patterns
[Tue Feb 19 10:23:02.731445 2019] [:error] [pid 4147] [remote 10.2.200.108:52] mod_wsgi (pid=4147): Exception occurred processing WSGI script '/usr/lib/python2.7/site-packages/adagios/wsgi.py'.
[Tue Feb 19 10:23:02.731490 2019] [:error] [pid 4147] [remote 10.2.200.108:52] Traceback (most recent call last):
[Tue Feb 19 10:23:02.731507 2019] [:error] [pid 4147] [remote 10.2.200.108:52] File "/usr/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 157, in **call**
[Tue Feb 19 10:23:02.731540 2019] [:error] [pid 4147] [remote 10.2.200.108:52] response = self.get_response(request)
[Tue Feb 19 10:23:02.731550 2019] [:error] [pid 4147] [remote 10.2.200.108:52] File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 124, in get_response
[Tue Feb 19 10:23:02.731563 2019] [:error] [pid 4147] [remote 10.2.200.108:52] response = self._middleware_chain(request)
[Tue Feb 19 10:23:02.731570 2019] [:error] [pid 4147] [remote 10.2.200.108:52] File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 43, in inner
[Tue Feb 19 10:23:02.731582 2019] [:error] [pid 4147] [remote 10.2.200.108:52] response = response_for_exception(request, exc)
[Tue Feb 19 10:23:02.731589 2019] [:error] [pid 4147] [remote 10.2.200.108:52] File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
[Tue Feb 19 10:23:02.731600 2019] [:error] [pid 4147] [remote 10.2.200.108:52] response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
[Tue Feb 19 10:23:02.731607 2019] [:error] [pid 4147] [remote 10.2.200.108:52] File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 139, in handle_uncaught_exception
[Tue Feb 19 10:23:02.731617 2019] [:error] [pid 4147] [remote 10.2.200.108:52] return debug.technical_500_response(request, *exc_info)
[Tue Feb 19 10:23:02.731624 2019] [:error] [pid 4147] [remote 10.2.200.108:52] File "/usr/lib/python2.7/site-packages/django/views/debug.py", line 84, in technical_500_response
[Tue Feb 19 10:23:02.731636 2019] [:error] [pid 4147] [remote 10.2.200.108:52] html = reporter.get_traceback_html()
[Tue Feb 19 10:23:02.731642 2019] [:error] [pid 4147] [remote 10.2.200.108:52] File "/usr/lib/python2.7/site-packages/django/views/debug.py", line 328, in get_traceback_html
[Tue Feb 19 10:23:02.731653 2019] [:error] [pid 4147] [remote 10.2.200.108:52] return t.render(c)
[Tue Feb 19 10:23:02.731660 2019] [:error] [pid 4147] [remote 10.2.200.108:52] File "/usr/lib/python2.7/site-packages/django/template/base.py", line 207, in render
[Tue Feb 19 10:23:02.731671 2019] [:error] [pid 4147] [remote 10.2.200.108:52] return self._render(context)
[Tue Feb 19 10:23:02.731678 2019] [:error] [pid 4147] [remote 10.2.200.108:52] File "/usr/lib/python2.7/site-packages/django/template/base.py", line 199, in _render
[Tue Feb 19 10:23:02.731689 2019] [:error] [pid 4147] [remote 10.2.200.108:52] return self.nodelist.render(context)
[Tue Feb 19 10:23:02.731696 2019] [:error] [pid 4147] [remote 10.2.200.108:52] File "/usr/lib/python2.7/site-packages/django/template/base.py", line 990, in render
[Tue Feb 19 10:23:02.731706 2019] [:error] [pid 4147] [remote 10.2.200.108:52] bit = node.render_annotated(context)
[Tue Feb 19 10:23:02.731713 2019] [:error] [pid 4147] [remote 10.2.200.108:52] File "/usr/lib/python2.7/site-packages/django/template/base.py", line 957, in render_annotated
[Tue Feb 19 10:23:02.731723 2019] [:error] [pid 4147] [remote 10.2.200.108:52] return self.render(context)
[Tue Feb 19 10:23:02.731730 2019] [:error] [pid 4147] [remote 10.2.200.108:52] File "/usr/lib/python2.7/site-packages/django/template/base.py", line 1040, in render
[Tue Feb 19 10:23:02.731740 2019] [:error] [pid 4147] [remote 10.2.200.108:52] output = self.filter_expression.resolve(context)
[Tue Feb 19 10:23:02.731750 2019] [:error] [pid 4147] [remote 10.2.200.108:52] File "/usr/lib/python2.7/site-packages/django/template/base.py", line 732, in resolve
[Tue Feb 19 10:23:02.731800 2019] [:error] [pid 4147] [remote 10.2.200.108:52] obj = template_localtime(obj, context.use_tz)
[Tue Feb 19 10:23:02.731821 2019] [:error] [pid 4147] [remote 10.2.200.108:52] File "/usr/lib/python2.7/site-packages/django/utils/timezone.py", line 195, in template_localtime
[Tue Feb 19 10:23:02.731847 2019] [:error] [pid 4147] [remote 10.2.200.108:52] return localtime(value) if should_convert else value
[Tue Feb 19 10:23:02.731869 2019] [:error] [pid 4147] [remote 10.2.200.108:52] File "/usr/lib/python2.7/site-packages/django/utils/timezone.py", line 213, in localtime
[Tue Feb 19 10:23:02.731895 2019] [:error] [pid 4147] [remote 10.2.200.108:52] timezone = get_current_timezone()
[Tue Feb 19 10:23:02.731917 2019] [:error] [pid 4147] [remote 10.2.200.108:52] File "/usr/lib/python2.7/site-packages/django/utils/timezone.py", line 97, in get_current_timezone
[Tue Feb 19 10:23:02.731954 2019] [:error] [pid 4147] [remote 10.2.200.108:52] return getattr(_active, "value", get_default_timezone())
[Tue Feb 19 10:23:02.731977 2019] [:error] [pid 4147] [remote 10.2.200.108:52] File "/usr/lib/python2.7/site-packages/django/utils/lru_cache.py", line 124, in wrapper
[Tue Feb 19 10:23:02.732004 2019] [:error] [pid 4147] [remote 10.2.200.108:52] result = user_function(*args, **kwds)
[Tue Feb 19 10:23:02.732026 2019] [:error] [pid 4147] [remote 10.2.200.108:52] File "/usr/lib/python2.7/site-packages/django/utils/timezone.py", line 79, in get_default_timezone
[Tue Feb 19 10:23:02.732053 2019] [:error] [pid 4147] [remote 10.2.200.108:52] return pytz.timezone(settings.TIME_ZONE)
[Tue Feb 19 10:23:02.732075 2019] [:error] [pid 4147] [remote 10.2.200.108:52] File "/usr/lib/python2.7/site-packages/pytz/**init**.py", line 156, in timezone
[Tue Feb 19 10:23:02.732102 2019] [:error] [pid 4147] [remote 10.2.200.108:52] if zone.upper() == 'UTC':
[Tue Feb 19 10:23:02.732132 2019] [:error] [pid 4147] [remote 10.2.200.108:52] AttributeError: 'NoneType' object has no attribute 'upper'

Please help me !!

**Comment by gardart** [comment]
I fixed the install guide
https://github.com/opinkerfi/adagios/wiki/Install-guide/2802a3513ea49f31f5574d6a5e716362b05c8320
