### ISSUE TITLE
python 3 support

### ISSUE THREAD

**Issue by tjyang** [opinkerfi/adagios#654]
I am trying to verify fedora install, on fedora 30,  from wiki.  
Looks like django for python2 is not available anymore.  pynag work with python3 but not adagios.
See R1 for my first countered issue.  

R1: https://stackoverflow.com/questions/56147071/modulenotfounderror-no-module-named-hotshot

**Comment by Cat5TV** [comment]
As python 2.7 is EOL this year, I'm preparing to move to python 3.8. Is Adagios support for > python 2.7 on the roadmap? Currently, it fails to compile.

**Comment by gardart** [comment]
Here is the PR https://github.com/opinkerfi/adagios/pull/662
It is not complete (errors in the unittests) but you could try that out...
