### ISSUE TITLE
scan network default with /28 subnet mask

### ISSUE THREAD

**Issue by tjyang** [opinkerfi/adagios#656]
* WHAT:  Please change /28 to /24 netmask.
* WHY : /24 is more frequent user case. 
* Adagios version on CentOS 7.6
```
 adagios-1.6.4-1.git.0.99b0df8.el7.noarch
```
* When select "Scan network", see following screenshot for nagios server on 192.168.1.111
![image](https://user-images.githubusercontent.com/378638/64299360-95396780-cf3e-11e9-9c37-aa320add05ce.png)

* References:
    * [scan_network.html](https://github.com/opinkerfi/adagios/blob/76934c9c1045483955d8791020d7a90f38e82dc6/adagios/okconfig_/templates/scan_network.html)

**Comment by palli** [comment]
Thank you for the bug report. Can you clarify what the problem and/or feature request is ?

**Comment by tjyang** [comment]
@palli , I edit the issue above.  Thanks for working on adagios project.

**Comment by tjyang** [comment]
@palli 

I replaced 28 with 24 to fix my concern.

```
-bash-4.2$ egrep 28 /usr/lib/python2.7/site-packages/adagios/okconfig_/views.py
                network_address = "%s/28" % my_ip
-bash-4.2$
```
