### ISSUE TITLE
Adagios on Centos 7 recently started receiving "Error while sending acknowledge command to the server." while acknowledging alerts 

### ISSUE THREAD

**Issue by chr00ted** [opinkerfi/adagios#668]
After some centos updates, not sure how long ago, I started receiving "Error while sending acknowledge command to the server." while acknowledging alerts. I am able to send email via the command line without issue.

Also if I go to reschedule checks, I also receive: Error while rescheduling checks. Error output printed in javascript console.

Any help would be greatly appreciated!

**Comment by chr00ted** [comment]
If anyone has this issue in the future, centos updates may have updated nagios. I resolved by re-running:

# Make sure nagios doesn't interfere
mkdir /etc/nagios/disabled
mv /etc/nagios/{nagios,cgi}.cfg /etc/nagios/disabled/

**Comment by chr00ted** [comment]
If anyone has this issue in the future, centos updates may have updated nagios. I resolved by re-running:

Make sure nagios doesn't interfere
mkdir /etc/nagios/disabled
mv /etc/nagios/{nagios,cgi}.cfg /etc/nagios/disabled/

**Comment by hakong** [comment]
This has been an issue for a long time with Naemon at least. If using Naemon, adagios will still try to use /etc/nagios/nagios.cfg even though the nagios config parameter is set to /etc/naemon/naemon.cfg. I have to delete /etc/nagios/nagios.cfg after every update. @gardart ?

**Comment by hakong** [comment]
Example if /etc/nagios/nagios.cfg exists.
If I move it to .old, this warning goes away.

![image](https://user-images.githubusercontent.com/4422113/86899607-c4d67480-c0f9-11ea-82f9-ecc48879ffa2.png)
![image](https://user-images.githubusercontent.com/4422113/86899859-0ff08780-c0fa-11ea-8193-bdeab1eec887.png)
![image](https://user-images.githubusercontent.com/4422113/86899883-1979ef80-c0fa-11ea-8d8e-44b5b13272e9.png)

**Comment by chr00ted** [comment]
thx
